import {test,expect} from '@playwright/test';
test.use({launchOptions:{args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']},permissions:['microphone','camera']});
test('local capture saves playable microphone/video with frames and does not stop call tracks',async({page})=>{
 page.on('pageerror',e=>console.log('HARNESS',e.message));page.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text());});
 await page.route('**/api/training/speech-review*',r=>r.fulfill({json:{version:1,model:'mock',language:'en',duration:3,findings:['pronunciation','fluency','intonation'].map(criterion=>({criterion,status:'effective',observation:'Mocked audible observation for UI testing.',suggestion:'',segments:[{id:'segment-0',start:0,end:3}]}))}}));
 await page.route('**/api/training/visual-review',r=>r.fulfill({json:{findings:['framing','lighting','visibility'].map(criterion=>({criterion,status:'insufficient_evidence',observation:'Synthetic camera image; no human presentation assessed.',suggestion:'',frameIds:[]}))}}));
 await page.route('**/capture-harness',r=>r.fulfill({contentType:'text/html',body:`<meta name="viewport" content="width=device-width,initial-scale=1"><div id="root" class="review-panel training-report-body" style="padding:16px"></div><script type="module" src="/tests/browser/captureHarness.ts"></script>`}));
 await page.goto('/capture-harness');await page.waitForFunction(()=>typeof (window as any).start==='function',null,{timeout:10000});await page.evaluate(()=>(window as any).start());await page.waitForTimeout(3200);await page.evaluate(()=>(window as any).finish());
 const result=await page.evaluate(async()=>{const w=window as any,c=w.clips.find((c:any)=>c.sessionId==='capture-test');return {live:w.tracksLive,bytes:c?.blob.size,frames:c?.frames.length,attempt:c?.attempt,type:c?.blob.type};});expect(result.live).toBe(true);expect(result.bytes).toBeGreaterThan(100);expect(result.frames).toBeGreaterThan(0);expect(result.attempt).toBe(1);expect(result.type).toContain('video/');await page.evaluate(()=>(window as any).show());await expect(page.locator('summary').filter({hasText:'Pronunciation clarity'})).toBeVisible();await expect(page.getByText('Synthetic camera image; no human presentation assessed.').first()).toBeVisible();await page.waitForFunction(()=>document.querySelector<HTMLVideoElement>('.call-review-clip video')!.readyState>=1);await page.screenshot({path:`artifacts/screenshots/call-media-${test.info().project.name}.png`,fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'Delete recording & feedback'}).click();await expect(page.locator('.call-review-clip')).toHaveCount(0);await page.evaluate(()=>(window as any).clean());
});
