import {test,expect} from '@playwright/test';
for(const lang of ['ar','en'])test(`${lang}: camera toggle keeps the same meeting (mocked transport, synthetic media)`,async({page})=>{
 const ar=lang==='ar';let starts=0,stops=0;const histories:any[]=[];
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.route('**/api/config',r=>r.fulfill({json:{ai:{configured:true},voice:{configured:true,languages:['ar','en']},avatar:{configured:true},videoCall:{configured:true},languages:['ar','en'],audit:{enabled:false}}}));
 await page.route('**/api/avatar/video-session',r=>{starts++;histories.push(r.request().postDataJSON().history);return r.fulfill({json:{id:'mock',url:'mock',meetingToken:'mock',conversationId:'mock',maxSessionSeconds:300}});});
 await page.route('**/api/ai-audit/**',r=>r.fulfill({json:{ok:true}}));
 await page.route('**/api/avatar/stop',r=>{stops++;return r.fulfill({json:{ok:true}});});
 await page.addInitScript(()=>{
  const ctx=new AudioContext(),dest=ctx.createMediaStreamDestination();const oscillator=ctx.createOscillator();oscillator.connect(dest);oscillator.start();
  (window as any).mockAudio=dest.stream.getAudioTracks()[0];(window as any).mediaRequests=[];
  (window as any).mockVideo=()=>{const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const c=canvas.getContext('2d')!;c.fillStyle='#486755';c.fillRect(0,0,640,480);c.fillStyle='#edf1de';c.font='24px sans-serif';c.textAlign='center';c.fillText('Synthetic camera · browser test',320,240);const s=canvas.captureStream(10);setTimeout(()=>c.fillRect(20,20,10,10),100);return s.getVideoTracks()[0];};
  navigator.mediaDevices.getUserMedia=async c=>{(window as any).mediaRequests.push(c);return new MediaStream([...(c?.audio?[(window as any).mockAudio.clone()]:[]),...(c?.video?[(window as any).mockVideo()]:[])]);};
  HTMLMediaElement.prototype.play=async()=>{};
 });
 await page.route('**/@daily-co_daily-js.js*',r=>r.fulfill({contentType:'text/javascript',body:`export default {createCallObject(){const v=window.mockVideo(),a=window.mockAudio.clone();return{on(name,fn){if(name==='app-message')window.emitMock=fn;},async join(){},participants(){return{remote:{local:false,session_id:'avatar',tracks:{video:{track:v},audio:{track:a}}}}},setLocalVideo(){},setLocalAudio(){},sendAppMessage(e){if(e.event_type==='conversation.respond')setTimeout(()=>window.emitMock({fromId:'avatar',data:{message_type:'conversation',event_type:'conversation.utterance',inference_id:'typed-reply',properties:{role:'pal',speech:'Mock reply to typed message.'}}}),10);},async setInputDevicesAsync(){},async leave(){},async destroy(){v.stop();a.stop();}}}};`}));
 await page.goto(`/?app=training&lang=${lang}`);
 const checkbox=page.getByRole('checkbox',{name:ar?'ابدأ والكاميرا مفعّلة':'Start with camera on'});
 await expect(checkbox).not.toBeChecked();
 if(ar)await checkbox.check();
 await page.getByRole('button',{name:ar?'ابدأ المناقشة':'Begin practice',exact:true}).click();
 const cameraOn=ar?'تشغيل الكاميرا':'Camera on',cameraOff=ar?'إيقاف الكاميرا':'Camera off';
 await expect(page.getByRole('button',{name:ar?cameraOff:cameraOn,exact:true})).toBeEnabled();
 expect(starts).toBe(1);expect(await page.evaluate(()=>(window as any).mediaRequests[0].video!==false)).toBe(ar);
 const stage=page.locator('.video-call-stage');const before=await stage.evaluate(e=>({w:e.clientWidth,h:e.clientHeight}));
 if(ar)await page.getByRole('button',{name:cameraOff,exact:true}).click();
 await expect(page.getByRole('button',{name:cameraOn,exact:true})).toBeEnabled();
 await page.getByRole('button',{name:cameraOn,exact:true}).click();await expect(page.getByRole('button',{name:cameraOff,exact:true})).toBeEnabled();
 await expect(page.locator('.video-call-self video')).toBeVisible();
 expect(await stage.evaluate(e=>({w:e.clientWidth,h:e.clientHeight}))).toEqual(before);expect(starts).toBe(1);
 await expect(page.locator('.workspace>.sidebar')).toBeVisible();
 const pageHeight=await page.evaluate(()=>document.documentElement.scrollHeight);
 await page.evaluate(()=>{for(let i=0;i<40;i++)(window as any).emitMock({fromId:'avatar',data:{message_type:'conversation',event_type:'conversation.utterance',inference_id:'long-'+i,properties:{role:i%2?'user':'pal',speech:'A longer conversation passage to check readable messages and stable layout. '.repeat(8)}}});});
 await expect(page.locator('.meeting-message')).toHaveCount(40);
 expect(await page.evaluate(()=>document.documentElement.scrollHeight)).toBeLessThanOrEqual(pageHeight+2);
 expect(await page.locator('.video-call-transcript').evaluate(e=>e.scrollHeight>e.clientHeight)).toBeTruthy();
 await page.screenshot({path:`artifacts/screenshots/meeting-${lang}-${test.info().project.name}.png`,fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:ar?'إيقاف الكاميرا':'Camera off',exact:true}).click();
 await expect(page.getByRole('button',{name:ar?'كتم الميكروفون':'Mute',exact:true})).toBeEnabled();
 expect(await stage.evaluate(e=>({w:e.clientWidth,h:e.clientHeight}))).toEqual(before);
 await page.locator('.meeting-composer input').fill('A typed contribution.');await page.locator('.meeting-composer button').click();await expect(page.locator('.meeting-message.assistant').last()).toContainText('Mock reply to typed message.');
 await page.getByRole('button',{name:ar?'متابعة بدون شخصية':'Continue without avatar',exact:true}).click();await expect(page.locator('.composer input')).toBeVisible();await expect.poll(()=>stops).toBe(1);
 await expect(page.locator('.turn')).toHaveCount(42);
 await page.getByRole('button',{name:ar?'تفعيل الصوت دون شخصية':'Enable voice without avatar'}).click();await expect(page.getByRole('button',{name:ar?'إيقاف الردود الصوتية':'Turn voice off'})).toBeVisible();expect(starts).toBe(1);
 await page.getByRole('button',{name:ar?'إعادة الاتصال بالشخصية':'Reconnect avatar'}).click();await expect(page.getByRole('button',{name:ar?'إنهاء المكالمة':'End call',exact:true})).toBeEnabled();await expect.poll(()=>starts).toBe(2);expect(histories[1]).toHaveLength(42);expect(histories[1].some((t:any)=>t.text==='A typed contribution.')).toBeTruthy();
 await page.getByRole('button',{name:ar?'إنهاء المكالمة':'End call',exact:true}).click();await expect.poll(()=>stops).toBe(2);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
