import {test,expect} from '@playwright/test';
for(const language of ['ar','en'] as const)test(`${language}: sourced discussion, retry and saved evidence (mocked model, real browser)`,async({page})=>{
 const ar=language==='ar';
 await page.route('**/api/config',route=>route.fulfill({json:{ai:{configured:true,missing:[]},voice:{configured:false,languages:['ar','en']},avatar:{configured:false,missing:[]},languages:['ar','en']}}));
 await page.route('**/api/training/followup',route=>route.fulfill({json:{text:ar?'هل يمكنك توضيح ذلك بمثال يرتبط بإجابتك؟':'Could you clarify that with an example related to your answer?',pointIds:['point-1'],readyForReview:false}}));
 await page.route('**/api/training/assess',route=>route.fulfill({json:{verdict:'partial',spokenFeedback:ar?'هذه ملاحظة اختبارية للمناقشة، وليست نتيجة من النموذج.':'This is a test discussion assessment, not a model result.',points:[{id:'point-1',status:'missing',answerQuote:'',explanation:ar?'ملاحظة اختبارية':'Test observation'}]}}));
 await page.goto(`/?app=training&lang=${language}`);
 await page.getByRole('button',{name:ar?'تدريب بأسئلة من المراجع':'Practise questions from sources',exact:true}).click();
 const context=page.getByLabel(ar?'سياق الحوار':'Dialogue context');
 await expect(context.locator('option')).toHaveCount(4);
 await context.selectOption('christianity');
 const questions=page.getByLabel(ar?'اختر سؤالًا':'Choose a question');
 await expect(questions.locator('option')).toHaveCount(94);
 const questionId=await questions.inputValue();
 await page.getByRole('textbox',{name:ar?'إجابتك':'Your answer',exact:true}).fill(ar?'أحتاج إلى التمييز بين كلام المؤلف وما يعتقده كل شخص.':'I should distinguish the author’s argument from each person’s beliefs.');
 await page.getByRole('button',{name:ar?'تابع المناقشة':'Continue discussion',exact:true}).click();
 await expect(page.locator('.reference-turn')).toHaveCount(3);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await expect(page.locator('html')).toHaveAttribute('dir',ar?'rtl':'ltr');
 await page.locator('.reference-practice').scrollIntoViewIfNeeded();
 await page.screenshot({path:`artifacts/screenshots/reference-discussion-${language}-${test.info().project.name}.png`,fullPage:true,animations:'disabled'});
 await page.getByRole('textbox',{name:ar?'إجابتك':'Your answer',exact:true}).fill(ar?'هذا توضيح إضافي لإجابتي.':'This is a further clarification of my answer.');
 await page.getByRole('button',{name:ar?'قيّم إجابتي بالمرجع':'Compare my answer with the reference',exact:true}).click();
 await expect(page.locator('.reference-assessment')).toBeVisible();
 await page.getByRole('button',{name:ar?'تدرّب على هذه النقطة':'Practise this point',exact:true}).click();
 await page.getByRole('textbox',{name:ar?'إجابتك':'Your answer',exact:true}).fill(ar?'هذه محاولتي الثانية.':'This is my second attempt.');
 await page.getByRole('button',{name:ar?'قيّم إجابتي بالمرجع':'Compare my answer with the reference',exact:true}).click();
 await expect(page.locator('.answer-attempt')).toHaveCount(2);
 await expect(page.locator('.reference-change').first()).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.screenshot({path:`artifacts/screenshots/reference-review-${language}-${test.info().project.name}.png`,fullPage:true,animations:'disabled'});
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('basira.reference-practice.v1')!));
 expect(saved[0].question.id).toBe(questionId);expect(saved[0].question.referenceVersion).toBeTruthy();expect(saved[0].attempts[0].turns).toHaveLength(4);expect(saved[0].attempts[1].turns).toHaveLength(2);
 await page.reload();
 await page.getByRole('button',{name:ar?'تدريب بأسئلة من المراجع':'Practise questions from sources',exact:true}).click();
 await page.locator('.saved-sessions summary').click();
 await page.getByRole('button',{name:ar?'فتح':'Open',exact:true}).click();
 await expect(page.locator('.answer-attempt')).toHaveCount(2);
 await page.getByRole('button',{name:ar?'حذف':'Delete',exact:true}).click();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('basira.reference-practice.v1')!))).toEqual([]);
});
