import 'fake-indexeddb/auto';
import React from 'react';
import {afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import {ContentReview} from '../src/ContentReview';
import {saveReport,listReports,deleteReport,getReport} from '../src/reportStore';
import {reportText,type ContentReport} from '../src/contentReviewTypes';
const part={passage:'example passage',status:'insufficient_evidence' as const,explanation:'No retrieved evidence; not a falsehood verdict.',referenceIds:[]};
const report:ContentReport={version:1,id:'argument-fixture',title:'Argument review fixture',language:'en',kind:'audio',createdAt:1,originalText:'',units:[{id:'a1',kind:'audio',text:'example passage',originalText:'machine original',confirmed:false,start:0,end:3}],frames:[],findings:[],coverage:'Fixture coverage',analysisStatus:'incomplete',arguments:{items:[{id:'arg1',unitId:'a1',passage:'example passage',evidenceKind:'other',evidence:part,reasoning:{...part,passage:''},conclusion:{...part,passage:''},references:[],uncertain:true,decision:'pending',reviewerNote:''}],summary:'Fixture summary',retrieval:'local_quran_only',incomplete:true}};
afterEach(async()=>{cleanup();vi.unstubAllGlobals();for(const r of await listReports())await deleteReport(r.id);});
it('saves human argument decisions and clears outdated argument judgments after transcript correction',async()=>{
 await saveReport(report);
 render(<ContentReview lang="en" onPractice={vi.fn()}/>);
 fireEvent.click(await screen.findByRole('button',{name:'Open'}));
 await screen.findByText('Evidence, reasoning and conclusion');
 fireEvent.click(screen.getByRole('button',{name:'Accept review'}));
 await waitFor(async()=>expect((await getReport(report.id))?.report.arguments?.items[0].decision).toBe('accepted'));
 fireEvent.click(screen.getByRole('button',{name:'Reject review'}));
 await waitFor(async()=>expect((await getReport(report.id))?.report.arguments?.items[0].decision).toBe('rejected'));
 fireEvent.click(screen.getByRole('button',{name:'Edit review'}));
 fireEvent.change(screen.getByLabelText('Reviewer note or correction'),{target:{value:'Human correction, not an AI conclusion'}});
 await waitFor(async()=>{const stored=(await getReport(report.id))!.report;expect(stored.arguments?.items[0].decision).toBe('edited');expect(reportText(stored)).toContain('Human correction, not an AI conclusion');});
 cleanup();render(<ContentReview lang="en" onPractice={vi.fn()}/>);
 fireEvent.click(await screen.findByRole('button',{name:'Open'}));
 expect(await screen.findByLabelText('Reviewer note or correction')).toHaveValue('Human correction, not an AI conclusion');
 fireEvent.change(screen.getByLabelText('Check the transcript a1'),{target:{value:'Corrected by human'}});
 await waitFor(async()=>{const stored=(await getReport(report.id))!.report;expect(stored.arguments).toBeUndefined();expect(stored.units[0].originalText).toBe('machine original');expect(stored.units[0].text).toBe('Corrected by human');});
});
