// @vitest-environment node
import {it,expect,vi} from 'vitest';
import {prepareSpeech,pcmWav,validateAudioAssessment} from '../server/audioAssessment';
import {sanitizeAudit} from '../server/aiAudit';
import {ModelProvider} from '../server/model';
const segments=[{id:'segment-0',start:0,end:8,audio:pcmWav(Buffer.alloc(32000*8))}];
const valid=()=>({findings:['pronunciation','fluency','intonation'].map(criterion=>({criterion,status:'practice',observation:'Audible hesitation in the supplied segment.',suggestion:'Complete a short phrase before pausing.',segmentIds:['segment-0']}))});
it('resolves times from actual segments, ignoring model-supplied times',()=>{const raw=valid();Object.assign(raw.findings[0],{start:123,end:999});expect(validateAudioAssessment(raw,segments,'test','en').findings[0].segments).toEqual([{id:'segment-0',start:0,end:8}]);});
it.each(['unknown','duplicate','missing','unsupported','no-exercise','empty-observation'])('blocks invalid audio evidence: %s',kind=>{const raw=valid();if(kind==='unknown')raw.findings[0].segmentIds=['invented'];if(kind==='duplicate')raw.findings[1]=raw.findings[0];if(kind==='missing')raw.findings.pop();if(kind==='unsupported')raw.findings[0].segmentIds=[];if(kind==='no-exercise')raw.findings[0].suggestion='';if(kind==='empty-observation')raw.findings[0].observation='';expect(()=>validateAudioAssessment(raw,segments,'test','en')).toThrow('invalid_audio_assessment');});
it('allows honest abstention without invented evidence or exercise',()=>{const raw=valid();for(const f of raw.findings){f.status='insufficient_evidence';f.segmentIds=[];f.suggestion='';}expect(validateAudioAssessment(raw,segments,'test','ar').findings.every(f=>!f.segments.length)).toBe(true);});
it('omits base64 audio from nested audit requests',()=>{const b=Buffer.from('private speech');const clean=JSON.stringify(sanitizeAudit({content:[{type:'input_audio',input_audio:{data:b.toString('base64'),format:'wav'}}]},{}));expect(clean).not.toContain(b.toString('base64'));expect(clean).toContain('sha256');expect(clean).toContain('audio');});
it('decodes real WAV and resolves bounded segment times; rejects invalid media',async()=>{const s=await prepareSpeech(pcmWav(Buffer.alloc(32000*13)),'audio/wav',AbortSignal.timeout(10000));expect(s.map(x=>[x.start,x.end])).toEqual([[0,12],[12,13]]);await expect(prepareSpeech(Buffer.from('bad'),'audio/wav',AbortSignal.timeout(10000))).rejects.toThrow('media_processing_failed');});
it('sends audio to an independent audio model and validates the response',async()=>{const request=vi.fn().mockResolvedValue(new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(valid())}}]})));const model=new ModelProvider({AI_AUDIT_ENABLED:'false',OPENAI_API_KEY:'test',AI_PROVIDER:'deepseek'},request);const result=await model.assessSpeech('ar',segments[0].audio,'audio/wav',AbortSignal.timeout(10000));expect(result.language).toBe('ar');const body=JSON.parse(request.mock.calls[0][1].body);expect(body.model).toBe('gpt-audio-1.5');expect(body.store).toBe(false);expect(body.messages[1].content[1].type).toBe('input_audio');});

it('discards unsolicited practice advice when evidence is insufficient',()=>{const raw=valid();for(const f of raw.findings){f.status='insufficient_evidence';f.segmentIds=[];}expect(validateAudioAssessment(raw,segments,'test','en').findings.every(f=>f.suggestion==='')).toBe(true);});
