import 'fake-indexeddb/auto';
import React from 'react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
import {ContentReview} from '../src/ContentReview';
import {getReport,listReports,deleteReport} from '../src/reportStore';
import {reportText,type ContentFinding} from '../src/contentReviewTypes';
const finding:ContentFinding={id:'f1',unitId:'text-1',start:0,end:25,passage:'112:1 «قل هو الله واحد»',quote:'قل هو الله واحد',category:'textual_mismatch',explanation:'Different wording in the cited verse.',reference:{id:'quran-112-1',title:'Quran 112:1',url:'https://tanzil.net/#112:1',excerpt:'قُلْ هُوَ اللَّهُ أَحَدٌ',provider:'Tanzil'},correction:'قُلْ هُوَ اللَّهُ أَحَدٌ',uncertain:false,decision:'pending',reviewerNote:'',editedCorrection:'',practiceEligible:true};
const calls:string[]=[];
function mockPipeline(){vi.stubGlobal('fetch',vi.fn(async(path:string,init?:RequestInit)=>{calls.push(path);const body=JSON.parse(typeof init?.body==='string'?init.body:'{}');let value:any;
 if(path.endsWith('/structure'))value={items:[{id:'item-1',unitId:body.units[0].id,passage:body.units[0].text,start:0,end:body.units[0].text.length,evidence:'',reasoning:'',conclusion:body.units[0].text,class:'other'}],morePossible:false};
 else if(path.endsWith('/assess-item')){const absent={status:'not_stated',explanation:'Not stated',suggestion:'',citations:[]};value={assessment:{item:body.structure.items[0],parts:{evidence:absent,reasoning:absent,conclusion:{status:'insufficient_evidence',explanation:'Insufficient source evidence.',suggestion:'',citations:[]}},uncertain:false,decision:'pending',reviewerNote:'',editedCorrection:''},retrieval:{items:[],status:'candidates_only',at:'now'}};}
 else if(path.endsWith('/summary'))value={overview:'Review your quotation before publication.',nextStep:'Compare it with the original reference.'};
 else if(path.includes('/media/audio'))value={duration:5,units:[{id:'a1',kind:'audio',start:0,end:5,text:'machine mistake',originalText:'machine mistake',confirmed:false}],note:'Approximate times'};
 else if(path.includes('/visual/'))value={version:1,kind:'video',summary:'Visual fixture',frames:[],descriptions:[],findings:[]};
 else if(path.includes('/media/frames'))value={duration:5,frames:[],note:'Sampled frames'};
 else throw Error('Unexpected route '+path);return Response.json(value);
}));}
beforeEach(async()=>{for(const r of await listReports())await deleteReport(r.id);calls.length=0;mockPipeline();vi.stubGlobal('matchMedia',vi.fn().mockReturnValue({matches:true}));Element.prototype.scrollTo=vi.fn();URL.createObjectURL=vi.fn().mockReturnValue('blob:fixture');URL.revokeObjectURL=vi.fn();});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
async function review(lang:'ar'|'en'){
 render(<ContentReview lang={lang} onPractice={vi.fn()}/>);fireEvent.change(screen.getByLabelText(lang==='ar'?'المحتوى المراد مراجعته':'Content to review'),{target:{value:finding.passage}});fireEvent.click(screen.getByRole('button',{name:lang==='ar'?'راجع المحتوى':'Review content'}));await screen.findByText('Review your quotation before publication.');
}
for(const lang of ['ar','en'] as const)it(`${lang}: extraction goes through retrieval and summary with no quotation check; decisions persist`,async()=>{
 await review(lang);expect(calls).toEqual(['/api/content/structure','/api/content/assess-item','/api/content/summary']);
 fireEvent.click(screen.getByRole('button',{name:lang==='ar'?'تعديل المراجعة':'Edit review'}));
 fireEvent.change(screen.getByLabelText(lang==='ar'?'صياغتك المقترحة':'Your proposed wording'),{target:{value:'Reviewer correction'}});
 await waitFor(async()=>expect((await listReports())[0]?.assessment?.items[0].editedCorrection).toBe('Reviewer correction'));
 const stored=(await listReports())[0];expect(stored.originalText).toBe(finding.passage);expect(reportText(stored)).toContain('Review your quotation');expect(stored.findings).toEqual([]);
 cleanup();render(<ContentReview lang={lang} onPractice={vi.fn()}/>);fireEvent.click(screen.getByText(new RegExp(lang==='ar'?'التقارير المحفوظة':'Saved reports')));fireEvent.click(await screen.findByRole('button',{name:lang==='ar'?'فتح':'Open'}));expect(await screen.findByLabelText(lang==='ar'?'صياغتك المقترحة':'Your proposed wording')).toHaveValue('Reviewer correction');fireEvent.click(screen.getByRole('button',{name:lang==='ar'?'حذف التقرير':'Delete report'}));await waitFor(async()=>expect(await getReport(stored.id)).toBeUndefined());
});
it('disables draft export while extraction is pending',async()=>{
 vi.stubGlobal('fetch',vi.fn(()=>new Promise(()=>{})));render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.change(screen.getByLabelText('Content to review'),{target:{value:finding.passage}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));expect(await screen.findByRole('button',{name:'Export readable report'})).toBeDisabled();
});
it('retains content and offers the same review action again if tuple extraction fails',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(Response.json({error:'invalid_content_evidence'},{status:502})));render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.change(screen.getByLabelText('Content to review'),{target:{value:finding.passage}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));expect(await screen.findByRole('alert')).toBeVisible();expect(screen.getByRole('button',{name:'Export readable report'})).toBeDisabled();expect(screen.getByRole('button',{name:'Resume review'})).toBeEnabled();await waitFor(async()=>expect((await listReports())[0].originalText).toBe(finding.passage));});
for(const kind of ['audio','video'] as const)it(`${kind}: one action extracts media without separate stage controls`,async()=>{const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:kind==='audio'?'Audio':'Video'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{types:['Files'],files:[new File(['fixture'],kind==='audio'?'a.wav':'a.mp4',{type:kind==='audio'?'audio/wav':'video/mp4'})]}});expect(screen.queryByRole('button',{name:'Create transcript'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Review content'}));await screen.findByText('Review your quotation before publication.');expect(calls.some(c=>c.includes('/media/audio'))).toBe(true);if(kind==='video')expect(calls.some(c=>c.includes('/media/frames'))).toBe(true);await waitFor(async()=>expect((await listReports())[0].units[0].originalText).toBe('machine mistake'));});
for(const lang of ['ar','en'] as const)it(`${lang}: rejects unsupported/multiple text uploads and preserves editor`,async()=>{const view=render(<ContentReview lang={lang} onPractice={vi.fn()}/>);const zone=view.container.querySelector('.upload-zone')!,file=new File(['hello'],'draft.txt',{type:'text/plain'});Object.defineProperty(file,'arrayBuffer',{value:async()=>new TextEncoder().encode('نص للمراجعة').buffer});fireEvent.drop(zone,{dataTransfer:{files:[file],types:['Files']}});await waitFor(()=>expect(view.container.querySelector('textarea')).toHaveValue('نص للمراجعة'));fireEvent.drop(zone,{dataTransfer:{files:[file,file],types:['Files']}});expect(await screen.findByRole('alert')).toHaveTextContent(lang==='ar'?'اختر ملفًا واحدًا':'Choose one file');fireEvent.drop(zone,{dataTransfer:{files:[new File(['pdf'],'a.pdf',{type:'application/pdf'})],types:['Files']}});expect(await screen.findByRole('alert')).toHaveTextContent(lang==='ar'?'اختر ملفًا نصيًا':'Choose a UTF-8');expect(view.container.querySelector('textarea')).toHaveValue('نص للمراجعة');});
for(const kind of ['audio','video'] as const)it(`${kind}: empty media never fabricates a report`,async()=>{const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:kind==='audio'?'Audio':'Video'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{types:['Files'],files:[new File([],kind==='audio'?'a.wav':'a.mp4',{type:kind==='audio'?'audio/wav':'video/mp4'})]}});expect(await screen.findByRole('alert')).toHaveTextContent('This file is empty');expect(await listReports()).toHaveLength(0);expect(fetch).not.toHaveBeenCalled();});
for(const lang of ['ar','en'] as const)for(const kind of ['audio','video'] as const)it(`${lang} ${kind}: illustrative reports remain labeled and cannot run live review`,async()=>{
 render(<ContentReview lang={lang} onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:kind==='audio'?(lang==='ar'?'صوت':'Audio'):(lang==='ar'?'فيديو':'Video')}));fireEvent.click(screen.getByRole('button',{name:lang==='ar'?'عرض تقرير توضيحي ببيانات تجريبية':'View an illustrative sample report'}));
 await waitFor(()=>expect(document.querySelector('.sample-report-notice')).toHaveTextContent(lang==='ar'?'تقرير توضيحي':'Illustrative report'),{timeout:3000});expect(screen.getByRole('button',{name:lang==='ar'?'راجع المحتوى':'Review content'})).toBeDisabled();fireEvent.click(screen.getAllByRole('button',{name:lang==='ar'?'قبول الملاحظة':'Accept finding'})[0]);await waitFor(async()=>expect((await listReports())[0].findings[0].decision).toBe('accepted'));const stored=(await listReports())[0];expect(stored.example).toBe(true);expect(reportText(stored)).toContain('مثال توضيحي');expect(fetch).not.toHaveBeenCalled();
});
it('cancels sample preparation without inventing or saving a result',async()=>{
 render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Audio'}));fireEvent.click(screen.getByRole('button',{name:'View an illustrative sample report'}));fireEvent.click(screen.getByRole('button',{name:'Cancel processing'}));await waitFor(()=>expect(screen.queryByText('Preparing the illustrative example…')).toBeNull());expect(await listReports()).toHaveLength(0);expect(fetch).not.toHaveBeenCalled();
});
it('keeps the original transcript and uses the reviewer correction on the next single-action review',async()=>{
 const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Audio'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{types:['Files'],files:[new File(['fixture'],'voice.wav',{type:'audio/wav'})]}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));await screen.findByText('Review your quotation before publication.');fireEvent.click(screen.getByRole('button',{name:'Back to content'}));fireEvent.click(screen.getByText('View and edit extracted text'));fireEvent.change(screen.getByLabelText('Check the transcript a1'),{target:{value:'Corrected transcript'}});fireEvent.click(screen.getByRole('checkbox',{name:'I checked this segment against the recording'}));fireEvent.click(screen.getByRole('button',{name:'Review content'}));await screen.findByText('Review your quotation before publication.');const requests=vi.mocked(fetch).mock.calls.filter(([path])=>String(path).endsWith('/structure'));const body=JSON.parse(String(requests.at(-1)![1]?.body));expect(body.units[0]).toMatchObject({text:'Corrected transcript',originalText:'machine mistake',confirmed:true,start:0,end:5});expect(calls.filter(c=>c.includes('/media/audio'))).toHaveLength(1);
});
it('shows the actual audio-extraction failure and retries the same preserved recording',async()=>{
 const normal=fetch;let failAudio=true;vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>failAudio&&path.includes('/media/audio')?Promise.resolve(Response.json({error:'empty_transcription'},{status:422})):normal(path,init)));
 const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Audio'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{files:[new File(['fixture'],'voice.wav',{type:'audio/wav'})],types:['Files']}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Export readable report'})).toBeDisabled();expect(calls.some(p=>p.endsWith('/structure'))).toBe(false);
 failAudio=false;fireEvent.click(screen.getByRole('button',{name:'Resume review'}));await screen.findByText('Review your quotation before publication.');expect(screen.queryByRole('alert')).toBeNull();
});
it('reviews a silent video and retains completed extraction stages on resume',async()=>{
 const normal=fetch;let failSummary=true,audioCalls=0,frameCalls=0;
 vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>{if(path.includes('/media/audio')){audioCalls++;return Promise.resolve(Response.json({error:'no_audio_track'},{status:422}));}if(path.includes('/media/frames')){frameCalls++;return Promise.resolve(Response.json({duration:3,frames:[{id:'f1',at:0,image:'data:image/png;base64,AA==',text:'Visible religious claim.'}],note:'Samples'}));}if(path.endsWith('/summary')&&failSummary)return Promise.resolve(Response.json({error:'model_unavailable'},{status:503}));return normal(path,init);}));
 const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Video'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{files:[new File(['fixture'],'silent.mp4',{type:'video/mp4'})],types:['Files']}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));await screen.findByText('Your findings are saved below; the automated overview could not be completed.');failSummary=false;fireEvent.click(screen.getByRole('button',{name:'Resume review'}));await screen.findByText('Review your quotation before publication.');expect(audioCalls).toBe(1);expect(frameCalls).toBe(1);
});
it('does not silently finish audio review when no usable transcript is returned',async()=>{
 const normal=fetch;vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>path.includes('/media/audio')?Promise.resolve(Response.json({duration:3,units:[],note:'No speech'})):normal(path,init)));
 const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Audio'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{files:[new File(['fixture'],'silent.wav',{type:'audio/wav'})],types:['Files']}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));expect(await screen.findByRole('alert')).toHaveTextContent('No readable text or speech');expect(screen.getByRole('button',{name:'Export readable report'})).toBeDisabled();
});
it('offers resume when a video extraction path fails after other paths succeed',async()=>{
 const normal=fetch;let failFrames=true,frameCalls=0;
 vi.stubGlobal('fetch',vi.fn((path:string,init?:RequestInit)=>{if(path.includes('/media/frames')){frameCalls++;if(failFrames)return Promise.resolve(Response.json({error:'media_processing_failed'},{status:422}));}return normal(path,init);}));
 const view=render(<ContentReview lang="en" onPractice={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'Video'}));fireEvent.drop(view.container.querySelector('.upload-zone')!,{dataTransfer:{files:[new File(['fixture'],'clip.mp4',{type:'video/mp4'})],types:['Files']}});fireEvent.click(screen.getByRole('button',{name:'Review content'}));await screen.findByText('Review your quotation before publication.');expect(screen.getByText(/One extraction path did not finish/)).toBeVisible();failFrames=false;fireEvent.click(screen.getByRole('button',{name:'Resume review'}));await waitFor(()=>expect(screen.queryByText(/One extraction path did not finish/)).toBeNull());expect(frameCalls).toBe(2);
});
