// @vitest-environment node
import {it,expect} from 'vitest';
import {attachContentPractice,openContentPractice} from '../server/contentPractice';
import {identifiedQuranReference} from '../server/contentSources';
import {judgmentPassages} from '../server/contentAssessment';
const env={OPENAI_API_KEY:'fixture-secret'};
function assessment(){const reference=identifiedQuranReference('Quran 112:1')!;const p={status:'not_stated',explanation:'Absent',suggestion:'',citations:[]};return {item:{id:'item-1',unitId:'u',passage:'Quran 112:1: قل هو الله واحد',evidence:'قل هو الله واحد',reasoning:'',conclusion:'',class:'quran',start:0,end:27},parts:{evidence:{status:'inconsistent_with_excerpt',explanation:'Quotation differs.',suggestion:'Check the original.',citations:[{id:'p1',sourceId:reference.id,source:'quran',locator:reference.title,quote:reference.excerpt,provenance:'identified',reference}]},reasoning:p,conclusion:p},uncertain:false,decision:'pending',reviewerNote:'',editedCorrection:''} as any;}
it('uses canonical Arabic verse and carries its original source identity',()=>{const ref=identifiedQuranReference('سورة الإخلاص، الآية الأولى')!;expect(ref.id).toBe('quran-112-1');expect(ref.excerpt).toContain('أَحَدٌ');expect(identifiedQuranReference('an unnamed book')).toBeUndefined();expect(identifiedQuranReference('Quran 112:999')).toBeUndefined();});
it('preserves identified provenance into judge packets',()=>{const ref=identifiedQuranReference('112:1')!;const result=judgmentPassages({items:[{candidates:[{id:ref.id,text:ref.excerpt,source:'quran',locator:ref.title,provenance:'identified',reference:ref}]}]} as any);expect(result[0].reference).toEqual(ref);expect(result[0].provenance).toBe('identified');});
it('issues tamper-resistant focused practice retaining exact source and criteria',()=>{const result=attachContentPractice(assessment(),'ar',env,1000);const decoded=openContentPractice(result.practice!.token,env,2000);expect(decoded.question.context).toBe('content_review');expect(decoded.question.evidence?.[0].quote).toBe(assessment().parts.evidence.citations[0].quote);expect(decoded.origin.passage).toBe(assessment().item.passage);expect(decoded.question.points).toHaveLength(3);expect(()=>openContentPractice(result.practice!.token+'x',env,2000)).toThrow();expect(()=>openContentPractice(result.practice!.token,env,8*86400000)).toThrow();});
it('does not offer source-verified practice for uncertain media or unidentified excerpts',()=>{for(const mutate of [(a:any)=>{a.uncertain=true;},(a:any)=>{a.parts.evidence.citations[0].provenance='unverified';},(a:any)=>{a.parts.evidence.status='insufficient_evidence';}]){const a=assessment();mutate(a);expect(attachContentPractice(a,'en',env).practice).toBeUndefined();}});

it('does not resolve ambiguous multi-verse attribution as one identified source',()=>{expect(identifiedQuranReference('Quran 112:1 and 16:125')).toBeUndefined();});
