import {describe,it,expect,vi,beforeEach} from 'vitest';
const sdk=vi.hoisted(()=>({head:vi.fn(),get:vi.fn(),del:vi.fn().mockResolvedValue(undefined),list:vi.fn()}));
vi.mock('@vercel/blob',()=>sdk);
vi.mock('@vercel/blob/client',()=>({handleUpload:vi.fn()}));
import {RetainedMedia} from '../server/retainedMedia';
function setup(){const rows=new Map<string,string>();const request=vi.fn(async(url:unknown,init:any)=>{if(String(url).includes('private.blob')){const range=init.headers.Range.match(/bytes=(\d+)-(\d+)/);return new Response(new Uint8Array(Number(range[2])-Number(range[1])+1),{status:206});}const [op,key,value]=JSON.parse(init.body);if(op==='SET')rows.set(key,value);return Response.json({result:op==='GET'?rows.get(key)||null:'OK'});}) as unknown as typeof fetch;return {rows,service:new RetainedMedia({BLOB_READ_WRITE_TOKEN:'secret',UPSTASH_REDIS_REST_URL:'https://redis.test',UPSTASH_REDIS_REST_TOKEN:'redis-secret'},request)};}
beforeEach(()=>vi.clearAllMocks());
describe('retained private evidence',()=>{
 it('requires both storage and Redis credentials',()=>{expect(new RetainedMedia({BLOB_READ_WRITE_TOKEN:'a',UPSTASH_REDIS_REST_URL:'b'}).configured).toBe(false);});
 it('rejects tampered handles and expires access after seven days',async()=>{const {service,rows}=setup(),g=await service.prepare('video/mp4',3,{});await expect(service.complete(g.handle.replace(/.$/,'z'))).rejects.toThrow('media_missing');const key=[...rows.keys()][0],row=JSON.parse(rows.get(key)!);row.expires=0;rows.set(key,JSON.stringify(row));await expect(service.complete(g.handle)).rejects.toThrow('media_expired');});
 it('retains analyzed bytes until explicit deletion',async()=>{const {service}=setup(),g=await service.prepare('video/mp4',3,{});sdk.head.mockResolvedValue({size:3});await service.complete(g.handle);sdk.get.mockResolvedValue({statusCode:200,stream:new ReadableStream({start(c){c.enqueue(new Uint8Array([1,2,3]));c.close();}})});expect((await service.bytes(g.handle,new AbortController().signal)).data.length).toBe(3);expect(sdk.del).not.toHaveBeenCalled();await service.remove(g.handle);await expect(service.metadata(g.handle,{})).rejects.toThrow('media_missing');});
 it('caps playback chunks below Vercel response limits',async()=>{const {service}=setup(),size=6*1024*1024,g=await service.prepare('video/mp4',size,{});sdk.head.mockResolvedValue({size,url:'https://test.private.blob.vercel-storage.com/example'});await service.complete(g.handle);const result=await service.playback(g.handle,'bytes=0-',new AbortController().signal);expect(result.bytes.length).toBe(2*1024*1024);await expect(service.playback(g.handle,'bytes=99999999-',new AbortController().signal)).rejects.toThrow('invalid_range');});
 it('cleans expired uploads but preserves current ready recordings',async()=>{const {service,rows}=setup(),g=await service.prepare('video/mp4',3,{});sdk.head.mockResolvedValue({size:3});await service.complete(g.handle);sdk.list.mockResolvedValue({hasMore:false,blobs:[{pathname:g.path,url:'https://blob.test/one',uploadedAt:new Date()}]});expect(await service.cleanup()).toBe(0);const key=[...rows.keys()].find(k=>k.startsWith('basira:media:v1:'))!,row=JSON.parse(rows.get(key)!);row.expires=0;rows.set(key,JSON.stringify(row));expect(await service.cleanup()).toBe(1);});
});
