import {MEDIA_MAX_MB,IMAGE_MAX_MB} from '../src/mediaLimits.js';
import {randomUUID,createHmac,timingSafeEqual} from 'node:crypto';
import {get,head,del,list} from '@vercel/blob';
import {handleUpload} from '@vercel/blob/client';
import type {Request} from 'express';
import {ApiError} from './validation.js';
const DAY=86400000,MAX=MEDIA_MAX_MB*1024*1024;
const TYPES=['image/png','image/jpeg','image/webp','audio/mpeg','audio/mp3','audio/mp4','audio/x-m4a','audio/wav','audio/x-wav','audio/ogg','audio/webm','video/mp4','video/webm','video/quicktime'];
type Row={id:string;path:string;mime:string;size:number;created:number;expires:number;ready:boolean;deleted?:boolean;scope:unknown;metadata?:unknown};
export class RetainedMedia{
 constructor(private env:NodeJS.ProcessEnv,private request:typeof fetch=fetch){}
 get configured(){return !!this.env.BLOB_READ_WRITE_TOKEN&&!!(this.env.UPSTASH_REDIS_REST_URL||this.env.KV_REST_API_URL)&&!!(this.env.UPSTASH_REDIS_REST_TOKEN||this.env.KV_REST_API_TOKEN);}
 private get token(){if(!this.configured)throw new ApiError('large_upload_unavailable',503);return this.env.BLOB_READ_WRITE_TOKEN!;}
 private async redis(args:unknown[]){const r=await this.request(this.env.UPSTASH_REDIS_REST_URL||this.env.KV_REST_API_URL!,{method:'POST',headers:{Authorization:`Bearer ${this.env.UPSTASH_REDIS_REST_TOKEN||this.env.KV_REST_API_TOKEN}`,'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(8000)});const d=await r.json();if(!r.ok||d.error)throw new ApiError('media_storage_unavailable',503);return d.result;}
 private key(id:string){return 'basira:media:v1:'+id;}
 private sign(id:string){return createHmac('sha256',this.token).update('retained:'+id).digest('hex');}
 private identify(handle:unknown){if(typeof handle!=='string'||!/^\d+-[a-f0-9-]+\.[a-f0-9]{64}$/.test(handle))throw new ApiError('media_missing',404);const [id,sig]=handle.split('.');if(!timingSafeEqual(Buffer.from(sig),Buffer.from(this.sign(id))))throw new ApiError('media_missing',404);return id;}
 private async row(handle:unknown,ready=true){const id=this.identify(handle),raw=await this.redis(['GET',this.key(id)]);if(!raw)throw new ApiError('media_expired',410);const row=JSON.parse(raw) as Row;if(row.deleted)throw new ApiError('media_missing',404);if(row.expires<=Date.now())throw new ApiError('media_expired',410);if(ready&&!row.ready)throw new ApiError('media_not_ready',409);return row;}
 private put(r:Row){return this.redis(['SET',this.key(r.id),JSON.stringify(r),'EX',30*86400]);}
 async prepare(mime:string,size:number,scope:unknown){if(!TYPES.includes(mime)||!Number.isInteger(size)||size<=0||size>(mime.startsWith('image/')?IMAGE_MAX_MB*1024*1024:MAX))throw new ApiError('media_size_limit',413);if(JSON.stringify(scope||{}).length>1000)throw new ApiError('invalid_upload');const id=Date.now()+'-'+randomUUID(),handle=id+'.'+this.sign(id),r:Row={id,path:'review-media/'+id,mime,size,created:Date.now(),expires:Date.now()+7*DAY,ready:false,scope};await this.put(r);return {handle,path:r.path,expires:r.expires};}
 async authorize(req:Request){return handleUpload({request:req,body:req.body,token:this.token,onBeforeGenerateToken:async(path,payload)=>{const r=await this.row(payload,false);if(path!==r.path||r.ready||r.created<Date.now()-600000)throw new ApiError('invalid_upload');return {allowedContentTypes:[r.mime],maximumSizeInBytes:r.size,addRandomSuffix:false,allowOverwrite:false,validUntil:Date.now()+600000};}});}
 async complete(handle:unknown){const r=await this.row(handle,false);const info=await head(r.path,{token:this.token});if(info.size!==r.size)throw new ApiError('invalid_upload');r.ready=true;await this.put(r);return {handle,expires:r.expires};}
 async metadata(handle:unknown,metadata:unknown){const r=await this.row(handle);if(JSON.stringify(metadata).length>750000)throw new ApiError('content_too_long',413);r.metadata=metadata;await this.put(r);return {saved:true};}
 async remove(handle:unknown){const id=this.identify(handle),raw=await this.redis(['GET',this.key(id)]);if(!raw)return;const r=JSON.parse(raw) as Row;await del(r.path,{token:this.token});r.deleted=true;await this.put(r);}
 async bytes(handle:unknown,signal:AbortSignal){const r=await this.row(handle);const value=await get(r.path,{access:'private',token:this.token,useCache:false,abortSignal:signal});if(!value||value.statusCode!==200)throw new ApiError('media_missing',404);const reader=value.stream.getReader(),parts:Buffer[]=[];let size=0;try{for(;;){const chunk=await reader.read();if(chunk.done)break;size+=chunk.value.length;if(size>r.size||size>MAX)throw new ApiError('media_size_limit',413);parts.push(Buffer.from(chunk.value));}}finally{await reader.cancel().catch(()=>{});}if(size!==r.size)throw new ApiError('invalid_upload');return {data:Buffer.concat(parts),mime:r.mime};}
 async playback(handle:unknown,range:string|undefined,signal:AbortSignal){const r=await this.row(handle),match=range?.match(/^bytes=(\d+)-(\d*)$/);if(range&&!match)throw new ApiError('invalid_range',416);const start=Number(match?.[1]||0),requested=match?.[2]?Number(match[2]):r.size-1,end=Math.min(requested,start+2*1024*1024-1,r.size-1);if(!Number.isSafeInteger(start)||start<0||start>=r.size||end<start)throw new ApiError('invalid_range',416);const info=await head(r.path,{token:this.token});if(!new URL(info.url).hostname.endsWith('.private.blob.vercel-storage.com'))throw new ApiError('media_storage_unavailable',503);const response=await this.request(info.url,{headers:{Authorization:`Bearer ${this.token}`,Range:`bytes=${start}-${end}`},redirect:'error',signal});if(response.status!==206)throw new ApiError('media_storage_unavailable',503);const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length!==end-start+1)throw new ApiError('invalid_upload');return {bytes,mime:r.mime,start,end,total:r.size};}
 async cleanup(){let cursor=await this.redis(['GET','basira:media:cleanup-cursor'])||undefined,removed=0;const deadline=Date.now()+60000;do{const page=await list({prefix:'review-media/',limit:10,cursor,token:this.token});for(const b of page.blobs){const id=b.pathname.slice('review-media/'.length),raw=await this.redis(['GET',this.key(id)]),r=raw?JSON.parse(raw) as Row:null;if((r?.ready?r.expires<=Date.now():b.uploadedAt.getTime()<Date.now()-3600000)||r?.deleted){await del(b.url,{token:this.token});if(r){r.deleted=true;await this.put(r);}removed++;}}cursor=page.hasMore?page.cursor:undefined;}while(cursor&&Date.now()<deadline);await this.redis(['SET','basira:media:cleanup-cursor',cursor||'']);return removed;}
}
