import {postContentMedia} from './contentUpload';
import {useEffect,useRef,useState} from 'react';
import {AUDIO_CRITERIA} from './audioAssessment';
import {getReviewClips,saveReviewClip,removeReviewClip,type ReviewClip} from './callReviewMedia';
import type {Lang} from './content';
import {api} from './api';
function Clip({clip,lang,onDelete,onPractice}:{clip:ReviewClip;lang:Lang;onDelete:()=>void;onPractice?:(criterion:string)=>void}){
 const ar=lang==='ar',player=useRef<HTMLVideoElement|null>(null),[url,setUrl]=useState(''),[frame,setFrame]=useState(clip.frames[0]?.id),[error,setError]=useState(false);const stopAt=useRef<number|undefined>(undefined);
 useEffect(()=>{const u=URL.createObjectURL(clip.blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[clip.id]);
 const selected=clip.frames.find(f=>f.id===frame);const fmt=(v:number)=>v.toLocaleString(lang,{maximumFractionDigits:1});
 return <article className="call-review-clip"><header><strong>{ar?'تسجيلك':'Your recording'} · {new Date(clip.at).toLocaleTimeString(lang)}</strong><button className="text-button" onClick={onDelete}>{ar?'حذف التسجيل وملاحظاته':'Delete recording & feedback'}</button></header><video ref={player} src={url||undefined} controls playsInline preload="metadata" className={clip.blob.type.startsWith('audio')?'audio-only':''} aria-label={ar?'تسجيل المتدرّب':'Trainee recording'} onError={()=>setError(true)} onTimeUpdate={()=>{if(player.current&&stopAt.current!==undefined&&player.current.currentTime>=stopAt.current){player.current.pause();stopAt.current=undefined;}}}/>{error&&<p role="status">{ar?'تعذّر تشغيل التسجيل في هذا المتصفح.':'This browser could not play the recording.'}</p>}
 {clip.audio?.findings.map(f=><details className="quality-finding" key={f.criterion} data-status={f.status==='practice'?'needs_attention':f.status} open={f.status==='practice'}><summary>{AUDIO_CRITERIA[f.criterion][lang]}<small>{f.status==='effective'?(ar?'نقطة قوة مسموعة':'Audible strength'):f.status==='practice'?(ar?'اقتراح للتدريب':'Practice suggestion'):(ar?'لا تكفي الأدلة':'Insufficient evidence')}</small></summary><p>{f.observation}</p>{f.suggestion&&<p>{f.suggestion}</p>}{f.status==='practice'&&onPractice&&<button className="primary" onClick={()=>onPractice(f.criterion)}>{ar?'جرّب هذه الملاحظة في إعادة التدريب':'Try this suggestion in a retry'}</button>}{f.segments.map(s=><button key={s.id} className="secondary" onClick={()=>{if(player.current){stopAt.current=s.end;player.current.currentTime=s.start;void player.current.play().catch(()=>setError(true));}}}>{ar?'استمع':'Listen'} {fmt(s.start)}–{fmt(s.end)} {ar?'ث':'s'}</button>)}</details>)}
 {clip.frames.length>0&&<section className="camera-evidence"><h4>{ar?'لقطاتك ودليل الملاحظة':'Your frames and observation evidence'}</h4>{selected&&<figure><img src={selected.image} alt={ar?'لقطة كاميرا محفوظة من محاولتك':'Saved camera frame from your attempt'}/><figcaption>{fmt(selected.time)} {ar?'ثانية من هذا المقطع':'seconds into this clip'}</figcaption></figure>}<div>{clip.frames.map(f=><button key={f.id} className="secondary" aria-pressed={frame===f.id} onClick={()=>{setFrame(f.id);if(player.current)player.current.currentTime=f.time;}}>{fmt(f.time)} {ar?'ث':'s'}</button>)}</div>{clip.visual?.findings.map(f=><article key={f.criterion}><h5>{({framing:ar?'تكوين الإطار':'Framing',lighting:ar?'الإضاءة':'Lighting',visibility:ar?'وضوح الصورة':'Visibility'})[f.criterion]}</h5><p>{f.observation}</p>{f.suggestion&&<p>{f.suggestion}</p>}{f.frameIds.map(id=><button className="text-button" key={id} onClick={()=>setFrame(id)}>{ar?'اعرض اللقطة الداعمة':'Show supporting frame'} {clip.frames.findIndex(g=>g.id===id)+1}</button>)}</article>)}</section>}
 {clip.error&&<p role="status">{ar?'لم تكتمل بعض الملاحظات؛ التسجيل محفوظ ويمكن إعادة التحليل.':'Some observations could not be completed. The recording is saved and can be analyzed again.'}</p>}
 </article>;
}
export function CallMediaReview({sessionId,recordId,attempt,lang,onPractice}:{onPractice?:(criterion:string)=>void;sessionId:string;recordId:string;attempt:number;lang:Lang}){
 const ar=lang==='ar',[clips,setClips]=useState<ReviewClip[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(false);const running=useRef(false),abort=useRef<AbortController|null>(null),alive=useRef(true);
 async function analyze(rows:ReviewClip[]){if(running.current)return;running.current=true;setBusy(true);const c=new AbortController();abort.current=c;try{for(const original of rows){if(c.signal.aborted)break;const row:ReviewClip={...original,error:undefined};try{if(!row.audio){const response=await postContentMedia(`/api/training/speech-review?language=${lang}`,row.blob,AbortSignal.any([c.signal,AbortSignal.timeout(90000)]));const data=await response.json();if(!response.ok)throw Error('audio_review_failed');row.audio=data;}if(row.frames.length&&!row.visual)row.visual=await api('/api/training/visual-review',{language:lang,frames:row.frames},c.signal,90000);}catch{if(c.signal.aborted)break;row.error='review_failed';}if(c.signal.aborted)break;await saveReviewClip(row);if(alive.current)setClips(prev=>prev.map(p=>p.id===row.id?row:p));}}catch{if(alive.current)setError(true);}finally{running.current=false;if(alive.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;void getReviewClips().then(rows=>{if(!alive.current)return;const selected=rows.filter(r=>r.sessionId===sessionId&&r.recordId===recordId&&r.attempt===attempt).sort((a,b)=>a.at-b.at);setClips(selected);setLoading(false);void analyze(selected.filter(r=>!r.error&&(!r.audio||r.frames.length&&!r.visual)));}).catch(()=>{setLoading(false);setError(true);});return()=>{alive.current=false;abort.current?.abort();};},[sessionId,recordId,attempt]);
 return <section className="call-media-review"><h3>{ar?'أداؤك من تسجيلك':'Delivery from your recording'}</h3><details className="recording-scope"><summary>{ar?'حفظ التسجيل وحدود المراجعة':'Recording privacy and review scope'}</summary><p className="scope-note">{ar?'المقاطع واللقطات محفوظة على هذا الجهاز، مع نسخة سحابية خاصة عند توفرها، حتى ٧ أيام، وقد تُحذف الأقدم عند بلوغ حد التخزين. الملاحظات تخص المقاطع واللقطات المعروضة فقط. لا نقيس المشاعر أو الشخصية أو الثقة. قد يلتقط الميكروفون ضوضاء أو أصواتًا أخرى؛ لا يمكن ضمان عزل صوتك. يُحجب الصوت أثناء كلام الشخصية والكتم؛ هذه الفترات ليست وقفات محسوبة عليك. يمكنك مراجعة حركاتك بنفسك في الفيديو، دون تصنيف آلي للغة الجسد.':'Clips and frames stay on this device, with a private cloud copy when available, for up to 7 days; older media may be removed at the storage limit. Observations cover only the shown media, not emotions, personality or confidence. Microphone audio may contain background voices; speaker isolation is not guaranteed. Audio is suppressed during avatar speech and mute; these intervals are not learner pauses. Watch your gestures yourself in the video; body language is not automatically rated.'}</p></details>{loading&&<p role="status">{ar?'جارٍ فتح تسجيلاتك…':'Opening your recordings…'}</p>}{busy&&<p className="media-analysis-progress" role="status">{ar?'نستمع إلى تسجيلك ونراجع اللقطات… يمكنك قراءة مراجعة المحتوى الآن.':'Listening to your recording and checking frames… Your content review is available now.'}</p>}{!loading&&!clips.length&&<p>{ar?'تتوفر مراجعة الكلمات لهذه المحاولة، لكن لا يتوفر تسجيل على هذا الجهاز لتحليل الأداء الصوتي. جرّب إعادة التدريب بالصوت للحصول على ملاحظات من تسجيلك.':'Your words can be reviewed, but no recording is available on this device for delivery analysis. Try a spoken retry to receive feedback from your recording.'}</p>}{error&&<p role="alert">{ar?'تعذّر الوصول إلى التخزين المحلي.':'Local recording storage is unavailable.'}</p>}{clips.map(clip=><Clip key={clip.id} clip={clip} lang={lang} onPractice={onPractice} onDelete={()=>{abort.current?.abort();void removeReviewClip(clip.id).then(()=>setClips(rows=>rows.filter(r=>r.id!==clip.id))).catch(()=>setError(true));}}/>)}{!busy&&clips.some(c=>c.error)&&<button className="secondary" onClick={()=>void analyze(clips.filter(c=>c.error))}>{ar?'أعد تحليل التسجيلات غير المكتملة':'Retry incomplete recording reviews'}</button>}</section>;
}
