import {retainMedia,rememberMedia,deleteCloudMedia,saveMediaMetadata,type MediaReference} from './retainedMedia';
import type {AudioAssessment} from './audioAssessment';
export type VisualReview={findings:{criterion:'framing'|'lighting'|'visibility';status:'effective'|'practice'|'insufficient_evidence';observation:string;suggestion:string;frameIds:string[]}[]};
export type ReviewClip={id:string;sessionId:string;recordId:string;attempt:number;at:number;duration:number;mediaRef?:MediaReference;blob:Blob;frames:{id:string;time:number;image:string}[];audio?:AudioAssessment;visual?:VisualReview;error?:string};
const DB='basira-call-review-v1';const deleted=new Set<string>();
async function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('clips',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function transaction<T>(mode:IDBTransactionMode,work:(s:IDBObjectStore)=>IDBRequest<T>):Promise<T>{const db=await open();try{return await new Promise<T>((resolve,reject)=>{const tx=db.transaction('clips',mode),r=work(tx.objectStore('clips'));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
export async function getReviewClips(){const rows=await transaction('readonly',s=>s.getAll()) as ReviewClip[];const cutoff=Date.now()-7*86400000;for(const row of rows)if(row.at<cutoff)await removeReviewClip(row.id);return rows.filter(row=>row.at>=cutoff);}
export async function removeReviewClip(id:string){deleted.add(id);const row=await transaction<ReviewClip|undefined>('readonly',s=>s.get(id));await deleteCloudMedia(row?.mediaRef);return transaction('readwrite',s=>s.delete(id));}
export async function saveReviewClip(clip:ReviewClip,onLocalSaved?:()=>void){if(clip.blob.size>100*1024*1024)throw Error('recording_size_limit');const all=await getReviewClips();let bytes=all.filter(c=>c.id!==clip.id).reduce((n,c)=>n+c.blob.size,clip.blob.size);for(const old of all.sort((a,b)=>a.at-b.at)){if(old.id===clip.id)continue;if(old.at<Date.now()-7*86400000||bytes>100*1024*1024){await removeReviewClip(old.id);bytes-=old.blob.size;}}if(deleted.has(clip.id))return;await transaction('readwrite',s=>s.put(clip));onLocalSaved?.();rememberMedia(clip.blob,clip.mediaRef);try{clip.mediaRef??=await retainMedia(clip.blob,{workflow:'training',sessionId:clip.sessionId,recordId:clip.recordId,attempt:clip.attempt})||undefined;await saveMediaMetadata(clip.mediaRef,{...clip,blob:undefined});}finally{if(deleted.has(clip.id))await deleteCloudMedia(clip.mediaRef);else await transaction('readwrite',s=>s.put(clip));}}
export async function deleteSessionMedia(sessionId:string){for(const c of await getReviewClips())if(c.sessionId===sessionId)await removeReviewClip(c.id);}
