import type {Lang} from './content';
import type {ContentFinding,ContentReport,ReviewUnit} from './contentReviewTypes';
export function contentReviewExample(kind:'audio'|'video',language:Lang):ContentReport{
 const ar=language==='ar';
 const original='قال الله تعالى في سورة الإخلاص، الآية الأولى: «قل هو الله واحد».';
 const spoken=kind==='video'?'قال الله تعالى في سورة الإخلاص، الآية الأولى: «قل هو الله أحد».':original;
 const unit:ReviewUnit={id:'example-audio',kind:'audio',start:6,end:12,text:spoken,originalText:spoken,confirmed:false};
 const frame:ReviewUnit={id:'example-frame',kind:'frame',frameId:'example-frame',start:8,end:12,text:original,originalText:original,confirmed:false};
 const reference={id:'quran-112-1',title:'القرآن / Quran 112:1',url:'https://tanzil.net/#112:1',excerpt:'قُلْ هُوَ اللَّهُ أَحَدٌ',provider:'Tanzil Project · Arabic Simple 1.1'};
 const finding=(u:ReviewUnit,match=false):ContentFinding=>({id:`finding-${u.id}`,unitId:u.id,start:0,end:u.text.length,passage:u.text,quote:match?'قل هو الله أحد':'قل هو الله واحد',category:match?'textual_match':'textual_mismatch',explanation:match?(ar?'يطابق النص الصوتي المعروض ألفاظ المرجع.':'The displayed spoken transcript matches the reference wording.'):(ar?'يظهر في المقطع لفظ «واحد» بدلًا من «أحد» في المرجع. في التسجيل الحقيقي، يلزم مراجعة الصوت أو الإطار لتحديد ما إذا كان الاختلاف في المحتوى أم في الاستخراج.':'The passage uses “واحد” where the reference reads “أحد”. For real media, check the recording or frame to distinguish a content difference from an extraction error.'),reference,correction:match?null:reference.excerpt,uncertain:true,decision:'pending',reviewerNote:'',editedCorrection:'',practiceEligible:false});
 return {version:1,id:crypto.randomUUID(),example:true,title:ar?`مراجعة ${kind==='audio'?'صوت':'فيديو'}`:`${kind} review`,language,kind,createdAt:Date.now(),originalText:ar?'سيناريو معدّ مسبقًا؛ لا يوجد ملف أصلي مرفوع.':'Prepared scenario; no original media uploaded.',units:kind==='audio'?[unit]:[unit,frame],findings:kind==='audio'?[finding(unit)]:[finding(unit,true),finding(frame)],frames:kind==='video'?[{id:frame.id,at:8,image:'/examples/content-review-frame.svg',text:original}]:[],coverage:ar?'مرجع المثال: القرآن ١١٢:١ — مقارنة لفظ الاقتباس.':'Example reference: Quran 112:1 — quotation wording comparison.',analysisStatus:'complete',extractionNote:ar?'تفريغ تجريبي معدّ مسبقًا؛ لا يوجد تسجيل للتشغيل أو استخراج آلي في هذا المثال.':'Prepared sample transcript; this example contains no playable recording or automated extraction.',...(kind==='video'?{videoStatus:ar?'الإطار مصنوع للعرض؛ لا يثبت اكتمال تحليل الفيديو.':'The frame is an illustration; it does not demonstrate complete video analysis.'}:{})};
}
