export type Lang = 'ar'|'en';
export type Turn = {id:string; role:'user'|'assistant'; text:string; at:number; interrupted?:boolean; delivery?:'text'|'pending'|'complete'|'uncertain'};
export const copy = {
  ar: {
    tagline:'مساحة للحوار، وأفق للفهم', practice:'مساحة التدريب', journey:'رحلتك في بصيرة', title:'حوار أعمق. أثر أجمل.', subtitle:'تدرّب على الإصغاء، وعبّر عن فكرتك بحكمة. خطوة واحدة في كل مرة.',
    step1:'استعدّ',step2:'تحاور',step3:'تأمّل وتدرّب', scenario:'تدريب اليوم', scenarioTitle:'حين يبدأ الحوار بسؤال', scenarioDesc:'يسألك شخص عن معنى الإيمان في حياتك. كيف تبدأ حوارًا يحترم فضوله، ويفتح مساحة للفهم؟', skill:'المهارة المستهدفة',skillName:'الفهم قبل الإجابة', duration:'جلسة قصيرة · نحو دقيقتين',
    setting:'اختر مساحة حوارك', sessionLanguage:'لغة الجلسة',uiLanguage:'لغة الواجهة',arabic:'العربية',english:'English',
    voice:'محادثة صوتية',text:'تدريب كتابي', local:'تجربة محلية موجّهة',live:'اتصال حي', localNote:'تمرين كتابي بردود مُعدّة مسبقًا. لا يتصل بالذكاء الاصطناعي أو بخدمة صوت.', liveNote:'يُرسل صوتك للمعالجة عبر الإنترنت. لا نطلب الكاميرا. قد تحتفظ خدمة المعالجة بنص الجلسة.',
    unavailable:'الشخصية الصوتية غير متصلة بعد', unavailableDesc:'تحتاج إلى إعداد حساب الخدمة وصوت عربي وإنجليزي وأفاتار مرخّص. يمكنك تجربة التدريب الكتابي الآن.',
    start:'ابدأ المناقشة', starting:'جارٍ تجهيز الحوار…',ready:'على مهل، نحن هنا لنتدرّب',readyDesc:'ليس المطلوب جوابًا مثاليًا. ابدأ بالفضول، وأنصت لما وراء السؤال.', stageLabel:'مساحة الشخصية',awaiting:'بانتظار اتصال الشخصية', noAvatar:'ستظهر الشخصية المتحركة هنا عند تفعيل الخدمة',
    privacy:'مساحة آمنة للتعلّم',privacyDesc:'لا نستنتج مشاعرك أو معتقداتك. المراجعة تعتمد على كلماتك فقط.', tip:'خذ معك إلى الحوار',tipText:'سؤال صادق قد يفتح بابًا لا تفتحه إجابة طويلة.',
    transcript:'نص الحوار',hide:'إخفاء النص',show:'إظهار النص',you:'أنت', guide:'دليل التدريب',placeholder:'اكتب ردك هنا…',send:'إرسال',end:'إنهاء ومراجعة',listening:'أستمع إليك',thinking:'جارٍ إعداد الرد',speaking:'الشخصية تتحدث',typeHint:'أجب بطريقتك. يمكنك إنهاء الجلسة بعد أول رد.',
    mic:'تشغيل الميكروفون',mute:'كتم الميكروفون',interrupt:'مقاطعة الرد', interrupted:'لم يتأكد اكتمال الصوت — لا نفترض أنك سمعت الرد كاملًا',
    review:'مساحة للتأمّل',reviewTitle:'كل حوار يترك فرصة للنمو.',reviewSubtitle:'ارجع إلى كلماتك، ثم جرّب بداية أكثر إنصاتًا.', evidence:'من كلماتك',note:'ملاحظة تدريبية',noteText:'جرّب أن تبدأ بسؤال مفتوح، ثم عبّر عن فهمك لما يقصده الطرف الآخر قبل تقديم إجابتك. هذه دعوة للتأمّل وليست تقييمًا لمعتقدك.',source:'أصل نستأنس به',sourceLabel:'سورة النحل · الآية ١٢٥',excerpt:'مقتطف من النص القرآني الأصلي',interpretation:'تطبيق تدريبي: اختيار العبارة الأحسن والاستماع باحترام. هذا التطبيق ليس تفسيرًا للآية ولا فتوى.',retry:'أعد التدريب على هذه الملاحظة',back:'العودة للبداية',retryLabel:'محاولة جديدة · الفهم قبل الإجابة',retryHint:'هذه المرة، ابدأ بسؤال مفتوح يساعدك على فهم قصد المتحدث.', noEvidence:'لم تُسجَّل إجابة بعد. ابدأ حوارًا للحصول على ملاحظة مرتبطة بكلماتك.',
    offline:'انقطع الاتصال',offlineDesc:'توقّف التشغيل. نصك باقٍ في هذه الصفحة. يمكنك إنهاء الجلسة ومراجعتها أو بدء جلسة جديدة بعد عودة الاتصال.', reconnect:'بدء جلسة جديدة',error:'تعذّر بدء الاتصال',errorDesc:'تحقق من الاتصال وإذن الميكروفون وإعدادات الخدمة، ثم حاول مجددًا.',tryAgain:'حاول مجددًا', latency:'زمن الحدث الأول للرد',notMeasured:'لم يُقَس بعد', localMetric:'غير متاح في التدريب المحلي', words:'ردودك',footer:'بصيرة — نتعلّم لنفهم، ونتحاور لنقترب.',
  },
  en: {
    tagline:'Space for dialogue. Room for understanding.',practice:'Practice space',journey:'Your Basira journey',title:'Deeper dialogue. Lasting impact.',subtitle:'Practise listening and express your ideas with care. One thoughtful step at a time.',
    step1:'Prepare',step2:'Converse',step3:'Reflect & retry',scenario:'TODAY’S PRACTICE',scenarioTitle:'When dialogue begins with a question',scenarioDesc:'Someone asks what faith means in your life. How do you welcome their curiosity and make room for understanding?',skill:'YOUR FOCUS',skillName:'Understand before answering',duration:'A short session · about 2 minutes',
    setting:'Make room for conversation',sessionLanguage:'Session language',uiLanguage:'Interface language',arabic:'العربية',english:'English',voice:'Voice conversation',text:'Written practice',local:'Guided local preview',live:'Live connection',localNote:'A written exercise with prepared responses. No AI or voice service is connected.',liveNote:'Your audio is sent for online processing. No camera is requested. The processing service may retain the session transcript.',
    unavailable:'The voice avatar is not connected yet',unavailableDesc:'A configured service account, Arabic and English voices, and a licensed avatar are needed. Written practice is available now.',
    start:'Begin practice',starting:'Preparing your conversation…',ready:'Take your time. This is practice.',readyDesc:'You don’t need the perfect answer. Begin with curiosity and listen to the question beneath the words.',stageLabel:'AVATAR SPACE',awaiting:'Waiting for the avatar connection',noAvatar:'Your animated conversation partner will appear here once connected',
    privacy:'Room to learn safely',privacyDesc:'We do not infer your feelings or beliefs. Reflection uses only your words.',tip:'A thought to take with you',tipText:'An honest question can open a door that a long answer cannot.',
    transcript:'Conversation',hide:'Hide transcript',show:'Show transcript',you:'You',guide:'Practice guide',placeholder:'Write your response…',send:'Send',end:'Finish & reflect',listening:'Listening to you',thinking:'Preparing a response',speaking:'Avatar speaking',typeHint:'Respond in your own words. You can finish after your first response.',
    mic:'Enable microphone',mute:'Mute microphone',interrupt:'Interrupt response',interrupted:'Audio completion unconfirmed — we do not assume you heard the full response',
    review:'A MOMENT TO REFLECT',reviewTitle:'Every conversation leaves room to grow.',reviewSubtitle:'Revisit your words, then try a more attentive beginning.',evidence:'IN YOUR WORDS',note:'A practice note',noteText:'Try opening with a question, then reflect your understanding of the other person’s meaning before answering. This is a reflection prompt, not an assessment of your beliefs.',source:'A source for reflection',sourceLabel:'Surah An-Nahl · verse 16:125',excerpt:'Excerpt from the original Arabic Quran',interpretation:'Practice application: choose considerate words and listen respectfully. This application is not a Quranic commentary or a religious ruling.',retry:'Practise this note again',back:'Back to the beginning',retryLabel:'Another attempt · understand before answering',retryHint:'This time, begin with an open question that helps you understand the speaker’s intent.',noEvidence:'No response was recorded. Begin a conversation to reflect on your own words.',
    offline:'Connection lost',offlineDesc:'Playback has stopped. Your text remains on this page. Finish and reflect, or start a new session when you are back online.',reconnect:'Start a new session',error:'Could not connect',errorDesc:'Check your connection, microphone permission, and service configuration, then try again.',tryAgain:'Try again',latency:'First response event latency',notMeasured:'Not measured yet',localMetric:'Not available in local practice',words:'Your responses',footer:'Basira — learning to understand, talking to connect.',
  }
};
export const prompt = (l:Lang) => l==='ar'?'أود أن أفهم أكثر: ماذا يعني الإيمان في حياتك اليومية؟':'I’d like to understand: what does faith mean in your everyday life?';
export const followup = (l:Lang,n:number) => l==='ar' ? (n===1?'شكرًا لمشاركتك. ما السؤال الذي قد تطرحه عليّ لتفهم ما أبحث عنه؟':'خذ لحظة لتعيد صياغة ما فهمته من سؤالي، ثم شاركني مثالًا بسيطًا من تجربتك.') : (n===1?'Thank you for sharing. What might you ask me to understand what I am looking for?':'Take a moment to reflect what you understood from my question, then share a simple example from your experience.');
