import {useEffect,useRef,useState} from 'react';
import type {Lang} from './content';
import {assessmentLabels,assessmentParts,type AssessedItem,type ContentAssessment} from './contentAssessment';
import type {ContentFinding,ReviewUnit} from './contentReviewTypes';
import {categoryLabels} from './contentReviewTypes';
export function ContentAssessmentPanel({assessment,findings,units,lang,onChange,onFinding,onSeek,onPractice,onAssessmentPractice}:{assessment:ContentAssessment;findings:ContentFinding[];units:ReviewUnit[];lang:Lang;onChange:(id:string,patch:Partial<AssessedItem>)=>void;onFinding:(id:string,patch:Partial<ContentFinding>)=>void;onSeek:(unit:ReviewUnit)=>void;onPractice:(finding:ContentFinding)=>void;onAssessmentPractice?:(practice:{token:string;question:string})=>void}){
 const ar=lang==='ar',l=assessmentLabels[lang];const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>heading.current?.focus(),[]);
 const [filter,setFilter]=useState<'all'|'pending'|'attention'>('all');
 const needsAttention=(i:AssessedItem)=>assessmentParts.some(k=>['inconsistent_with_excerpt','insufficient_evidence','specialist_review'].includes(i.parts[k].status));
 const pending=assessment.items.filter(i=>i.decision==='pending').length;
 const items=assessment.items.filter(i=>filter==='all'||(filter==='pending'?i.decision==='pending':needsAttention(i)));
 return <section className="assessment-report" aria-label={ar?'تقرير مراجعة المحتوى':'Content assessment report'}>
  <h2 tabIndex={-1} ref={heading}>{ar?'من الملاحظة إلى قرار واضح':'From evidence to an editorial decision'}</h2>
  <p className="assessment-intro">{ar?'راجع مواضع الاتفاق والاختلاف وحدود الأدلة، ثم دوّن قرارك. المحتوى الأصلي محفوظ؛ لا تُطبَّق التصحيحات تلقائيًا.':'Examine the comparisons and evidence limits, then record your decision. Original content is preserved; corrections are never applied automatically.'}</p>
  <div className="assessment-metrics"><div><strong>{assessment.items.length} / {assessment.total}</strong><span>{ar?'مقاطع روجعت':'Passages assessed'}</span></div><div><strong>{assessment.items.filter(needsAttention).length}</strong><span>{ar?'تستحق انتباهك':'Need your attention'}</span></div><div><strong>{pending}</strong><span>{ar?'بانتظار قرارك':'Await your decision'}</span></div></div>
  <p className="scope-note">{ar?'مقارنة بالنصوص المتاحة، وليست موافقة دينية أو تصريح نشر. هوية كتب الاسترجاع وطبعاتها لم تُوثّق بعد؛ قبول ملاحظة لا يزيل هذا القيد.':'A comparison with available text, not religious approval or publication clearance. Retrieved books and editions remain unverified; accepting a finding does not remove this limitation.'}</p>
  {!assessment.complete&&<p className="assessment-incomplete" role="status">{ar?'التقرير جزئي. النتائج المكتملة محفوظة؛ استأنف لإكمال بقية المقاطع.':'This report is partial. Completed results are saved; resume to assess the remaining passages.'}</p>}
  {!assessment.total&&<p>{ar?'لم تُستخرج مقاطع قابلة للتقييم. هذا لا يعني اعتماد المحتوى.':'No assessable passages were extracted. This does not approve the content.'}</p>}
  {findings.length>0&&<section className="quotation-results"><h3>{ar?'فحص الاقتباسات والنِّسب':'Quotation and attribution checks'}</h3>{findings.map(f=><article key={f.id}><h4>{categoryLabels[f.category][lang]}</h4><blockquote dir="auto">{f.passage}</blockquote><p>{f.explanation}</p>{f.uncertain&&<p>{ar?'قد يكون الاختلاف ناتجًا عن التفريغ أو قراءة الصورة؛ تحقق من الأصل.':'The difference may come from transcription or image reading; check the original.'}</p>}{f.reference&&<details><summary>{f.reference.title}</summary><blockquote dir="auto">{f.reference.excerpt}</blockquote><a href={f.reference.url} target="_blank" rel="noreferrer">{ar?'افتح المرجع':'Open reference'}</a></details>}{f.correction&&<p>{ar?'تصحيح مقترح: ':'Suggested correction: '}{f.correction}</p>}<div className="assessment-decisions">{(['accepted','rejected','edited'] as const).map((d,n)=><button key={d} aria-pressed={f.decision===d} onClick={()=>onFinding(f.id,{decision:d})}>{ar?['قبول الملاحظة','رفض الملاحظة','تعديل الملاحظة'][n]:['Accept finding','Reject finding','Edit finding'][n]}</button>)}</div>{f.decision==='edited'&&<label>{ar?'تصحيحك التحريري':'Your editorial correction'}<textarea value={f.editedCorrection} onChange={e=>onFinding(f.id,{editedCorrection:e.target.value})}/></label>}{f.practiceEligible&&!f.uncertain&&['accepted','edited'].includes(f.decision)&&<button className="text-button" onClick={()=>onPractice(f)}>{ar?'تدرّب على هذه النقطة':'Practice this point'}</button>}</article>)}</section>}
  <nav className="assessment-filters" aria-label={ar?'تصفية المراجعة':'Filter findings'}>{(['all','pending','attention'] as const).map((f,n)=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{ar?['كل المقاطع','بانتظار قراري','تحتاج انتباهًا'][n]:['All passages','Awaiting my decision','Needs attention'][n]}</button>)}</nav>
  {items.map(({item,parts,uncertain,decision,reviewerNote,editedCorrection,practice},index)=><article className="assessment-item" key={item.id}><header><span className="eyebrow">{ar?'المقطع':'PASSAGE'} {index+1}</span><span>{decision==='pending'?(ar?'بانتظار المراجع':'Awaiting reviewer'):decision==='accepted'?(ar?'قبله المراجع':'Reviewer accepted'):decision==='rejected'?(ar?'رفضه المراجع':'Reviewer rejected'):(ar?'حرّره المراجع':'Reviewer edited')}</span></header><blockquote className="assessed-original" dir="auto">{item.passage}</blockquote><button className="text-button" onClick={()=>{const unit=units.find(u=>u.id===item.unitId);if(unit)onSeek(unit);}}>{ar?'عرض المقطع الأصلي':'View original passage'}</button>{uncertain&&<p className="assessment-incomplete">{ar?'النص مستخرج آليًا ولم يؤكده المراجع؛ راجع التسجيل أو الصورة قبل اعتماد الملاحظة.':'This extracted text has not been confirmed. Check the recording or image before accepting a finding.'}</p>}
   <div className="assessment-parts">{assessmentParts.map(key=><section key={key} data-status={parts[key].status}><h3>{l[key]}</h3><p dir="auto">{item[key]||l.not_stated}</p><span className="assessment-status">{l[parts[key].status]}</span><p dir="auto">{parts[key].explanation}</p>{parts[key].suggestion&&<div className="assessment-suggestion"><strong>{ar?'صياغة مقترحة للمراجعة':'Suggested wording to review'}</strong><p dir="auto">{parts[key].suggestion}</p></div>}{parts[key].citations.map(c=><details key={c.id}><summary>{ar?'المقتطف الداعم':'Supporting excerpt'} · <bdi>{c.locator||c.sourceId}</bdi></summary><blockquote dir="auto">{c.quote}</blockquote>{c.reference?<p><a href={c.reference.url} target="_blank" rel="noreferrer">{c.reference.title}</a> · {c.reference.provider} · <a href={c.licenseUrl} target="_blank" rel="noreferrer">CC BY 3.0</a></p>:<small>{ar?'من المجموعة المسترجعة؛ هوية المصدر لم تُوثق بعد.':'From the retrieved corpus; source identity remains unverified.'}</small>}</details>)}</section>)}</div>
   <div className="assessment-decisions">{(['accepted','rejected','edited'] as const).map((d,n)=><button key={d} aria-pressed={decision===d} onClick={()=>onChange(item.id,{decision:d})}>{ar?['قبول المراجعة','رفض المراجعة','تعديل المراجعة'][n]:['Accept review','Reject review','Edit review'][n]}</button>)}</div>{decision==='edited'&&<label>{ar?'صياغتك المقترحة':'Your proposed wording'}<textarea aria-label={ar?'صياغتك المقترحة':'Your proposed wording'} dir="auto" value={editedCorrection} onChange={e=>onChange(item.id,{editedCorrection:e.target.value})}/></label>}{practice&&!uncertain&&['accepted','edited'].includes(decision)&&onAssessmentPractice&&<button className="primary" onClick={()=>onAssessmentPractice(practice)}>{ar?'تدرّب على هذه النقطة':'Practice this point'}</button>}<label>{ar?'ملاحظة المراجع':'Reviewer note'}<textarea aria-label={ar?'ملاحظة المراجع':'Reviewer note'} dir="auto" value={reviewerNote} onChange={e=>onChange(item.id,{reviewerNote:e.target.value})}/></label>
  </article>)}{!items.length&&!!assessment.total&&<p>{ar?'لا توجد مقاطع ضمن هذه التصفية.':'No passages match this filter.'}</p>}
 </section>;
}
