import React,{useEffect,useState} from 'react';
import {ArrowUpRight,ArrowUpLeft,BookOpen,Globe2,MessageCircle,ArrowDown} from 'lucide-react';
import type {Lang} from './content';
import './landing.css';
const words={
 ar:{eyebrow:'مساحة للحوار، وعناية بالكلمة',title:'كلمات أوعى.\nحوار أعمق.',intro:'تدرّب قبل الحوار، وتحقّق قبل النشر. بصيرة تمنحك مساحة لتراجع كلماتك وتختار خطوتك التالية بعناية.',train:'ابدأ المناقشة',review:'راجع محتواك',enter:'ادخل إلى بصيرة',how:'كيف تعمل بصيرة؟',journey:'من الكلمة إلى المراجعة',one:'تحدّث',oneText:'حوار قصير يفتح مساحة للإنصات.',two:'راجع',twoText:'ارجع إلى كلماتك والأدلة المتاحة.',three:'جرّب مجددًا',threeText:'تدرّب على نقطة واحدة وقارن المحاولتين.',section:'مساحتان. غاية واحدة.',sectionText:'أن تصل كلماتك بوضوح واحترام.',trainingTitle:'قبل أن يبدأ الحوار',trainingText:'تحدّث مع شخصية مرئية أو اكتب إجابتك، ثم راجع ملاحظات مرتبطة بما قلت وجرّب إجابة أخرى.',reviewTitle:'قبل أن تنشر المحتوى',reviewText:'أضف نصك، وقارن الاقتباسات القرآنية بالمراجع المتاحة، ثم اتخذ قرارك التحريري بنفسك.',scope:'فحص الاقتباسات ونسبتها ضمن المصادر المتاحة؛ لا يشمل توثيق الحديث أو الفتاوى. القرار للمراجع البشري.',footer:'مساحة للتعلّم، وليست موافقة دينية أو إذنًا بالنشر.',language:'لغة الواجهة'},
 en:{eyebrow:'Space for dialogue. Care for every word.',title:'Thoughtful words.\nDeeper dialogue.',intro:'Practice before a conversation. Check before publishing. Basira gives you space to reflect on your words and choose your next step with care.',train:'Start training',review:'Review your content',enter:'Open Basira',how:'How does Basira work?',journey:'From words to reflection',one:'Speak',oneText:'A short dialogue with room to listen.',two:'Reflect',twoText:'Revisit your words and available evidence.',three:'Try again',threeText:'Practice one point and compare both attempts.',section:'Two spaces. One purpose.',sectionText:'Help your words reach others with clarity and respect.',trainingTitle:'Before the conversation',trainingText:'Speak with a visible character or type your answer. Review feedback tied to your words, then try another response.',reviewTitle:'Before you publish',reviewText:'Add your text, compare Quran quotations with available references, and make your own editorial decision.',scope:'Quotation and attribution checks within available sources; no hadith authentication or religious rulings. A human reviewer makes the decision.',footer:'A space for learning, not religious approval or publication clearance.',language:'Interface language'}
};
export function Landing(){
 const [lang,setLang]=useState<Lang>(()=>new URLSearchParams(window.location.search).get('lang')==='en'?'en':'ar');
 const t=words[lang],Arrow=lang==='ar'?ArrowUpLeft:ArrowUpRight;
 const href=(workflow:string)=>`/?app=${workflow}&lang=${lang}`;
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.title=lang==='ar'?'بصيرة | تدرّب قبل الحوار، وتحقّق قبل النشر':'Basira | Practice, reflect, grow';},[lang]);
 return <div className="landing" dir={lang==='ar'?'rtl':'ltr'}>
  <header className="landing-header"><a href="/" className="landing-brand" aria-label="بصيرة Basira"><svg viewBox="0 0 80 80" fill="none" aria-hidden="true"><path d="M40 9 8 40l32 31 32-31L40 9Z M40 18v44M18 40h44M24 24l32 32M56 24 24 56" stroke="currentColor" strokeWidth="1.4"/><circle cx="40" cy="40" r="16" stroke="currentColor"/><circle cx="40" cy="40" r="5" fill="currentColor"/></svg><img src="/brand/basira-wordmark.svg" alt="بصيرة"/></a><nav aria-label={lang==='ar'?'التنقل الرئيسي':'Main navigation'}><button className="language-button" aria-label={t.language} onClick={()=>setLang(lang==='ar'?'en':'ar')}><Globe2 size={16}/>{lang==='ar'?'English':'العربية'}</button><a className="landing-nav-link" href={href('training')}>{t.enter}<Arrow size={17}/></a></nav></header>
  <main className="landing-main"><section className="landing-hero" aria-labelledby="landing-title"><div className="landing-hero-copy"><p className="landing-kicker"><span/>{t.eyebrow}</p><h1 id="landing-title">{t.title.split('\n').map(line=><span key={line}>{line}</span>)}</h1><p className="landing-intro">{t.intro}</p><div className="landing-actions"><a className="landing-primary" href={href('training')}>{t.train}<Arrow size={20}/></a><a className="landing-secondary" href={href('content')}>{t.review}<BookOpen size={19}/></a></div><a className="landing-how" href="#how">{t.how}<ArrowDown size={15}/></a></div>
   <div className="landing-journey"><div className="landing-orbit" aria-hidden="true"><svg viewBox="0 0 300 240" fill="none"><path d="M150 16C114 70 66 83 34 120c32 37 80 50 116 104 36-54 84-67 116-104C234 83 186 70 150 16Z" stroke="currentColor"/><circle cx="150" cy="120" r="66" stroke="currentColor"/><path d="M150 42v156M72 120h156M99 69l102 102M201 69 99 171" stroke="currentColor"/><circle cx="150" cy="120" r="9" fill="currentColor"/></svg></div><p className="landing-journey-label">{t.journey}</p><ol>{[[t.one,t.oneText],[t.two,t.twoText],[t.three,t.threeText]].map(([title,body],i)=><li key={title}><span className="landing-step-number">{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{body}</p></div></li>)}</ol><span className="landing-language-note">العربية <span> / </span> English</span></div>
  </section>
  <section id="how" className="landing-workflows" aria-labelledby="workflow-title"><div className="landing-section-intro"><p className="landing-kicker">BASIRA</p><h2 id="workflow-title">{t.section}</h2><p>{t.sectionText}</p></div><div className="landing-paths"><article><MessageCircle size={27}/><h3>{t.trainingTitle}</h3><p>{t.trainingText}</p><a href={href('training')}>{t.train}<Arrow size={18}/></a></article><article><BookOpen size={27}/><h3>{t.reviewTitle}</h3><p>{t.reviewText}</p><a href={href('content')}>{t.review}<Arrow size={18}/></a><small>{t.scope}</small></article></div></section></main>
  <footer className="landing-footer"><span>بصيرة · BASIRA</span><p>{t.footer}</p></footer>
 </div>;
}
