import {WITHHELD_TRAINING_QUESTIONS,isSocialAcknowledgment} from './trainingEligibility';
import {CallMediaReview} from './CallMediaReview';
import {Check, ArrowUpRight, Circle, BookOpen, MessageSquare, Mic, Layers} from 'lucide-react';
import {SpokenDeliveryReview} from './SpokenDeliveryReview';
import {TrainingQualityReview} from './TrainingQualityReview';
import {useEffect,useRef,useState} from 'react';
import type {Lang} from './content';
import type {ReferenceRecord} from './referencePracticeTypes';
import {compareReferenceAttempts,type PointChange} from './referenceComparison';
const states={ar:{covered:'تناول هذه النقطة',missing:'نقطة لم تُذكر',contradicted:'مخالفة للمرجع'},en:{covered:'Covered',missing:'Not addressed',contradicted:'Conflicts with reference'}};
const verdicts={ar:{consistent:'متوافق مع الجواب المرجعي',partial:'متوافق جزئيًا مع المرجع',inconsistent:'يتضمن مخالفة للجواب المرجعي'},en:{consistent:'Consistent with reference',partial:'Partially consistent with reference',inconsistent:'Contains a conflict with the reference'}};
const changes:Record<Lang,Record<PointChange,string>>={ar:{unchanged:'لم يتغير التصنيف',newly_covered:'تناول النقطة في المحاولة الجديدة',no_longer_covered:'لم تُذكر النقطة في المحاولة الجديدة',conflict_identified:'رُصدت مخالفة في المحاولة الجديدة',conflict_not_repeated:'لم تتكرر المخالفة؛ النقطة لم تُشرح بعد',unavailable:'لا تتوفر مقارنة موثوقة'},en:{unchanged:'Classification unchanged',newly_covered:'Addressed in the new attempt',no_longer_covered:'Not addressed in the new attempt',conflict_identified:'A conflict was identified in the new attempt',conflict_not_repeated:'Conflict not repeated; point still not explained',unavailable:'No reliable comparison available'}};
export function ReferenceReview({record,lang,disabled,onRetry,onSpeak,onListenReference,referenceAudioActive,recordings}:{record:ReferenceRecord;lang:Lang;disabled:boolean;onRetry:(pointId?:string)=>void;onSpeak?:()=>void;onListenReference?:()=>void;referenceAudioActive?:boolean;recordings?:Record<string,string>}){
 const ar=lang==='ar',q=record.question,last=record.attempts.at(-1)!;
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{setPanel(record.attempts.length>1?'comparison':'evidence');setSelection(last.assessment.points.find(p=>p.status!=='covered')?.id||last.assessment.points[0]?.id);},[last.id]);
 const [selection,setSelection]=useState(last.assessment.points.find(p=>p.status!=='covered')?.id||last.assessment.points[0]?.id);
 const [comparisonId,setComparisonId]=useState(last.id);
 const selected=last.assessment.points.find(p=>p.id===selection)||last.assessment.points[0];
 const criterion=q.points.find(p=>p.id===selected?.id);
 const evidenceTurn=last.turns?.find(t=>t.id===selected?.turnId&&t.role==='user');
 const questionTurn=evidenceTurn&&last.turns?.slice(0,last.turns.indexOf(evidenceTurn)).reverse().find(t=>t.role==='assistant');
 const retry=record.attempts.find(a=>a.id===comparisonId)||last;
 const original=record.attempts[0];
 const [panel,setPanel]=useState(record.attempts.length>1?'comparison':'evidence');
 const [mediaAttempt,setMediaAttempt]=useState(record.attempts.length);
 const covered=last.assessment.points.filter(p=>p.status==='covered').length;
 const focus=selected;
 const tabs=[{id:'evidence',label:ar?'المعنى والدليل':'Answer & evidence',icon:BookOpen},{id:'quality',label:ar?'أسلوب التعبير':'Expression',icon:MessageSquare},{id:'recording',label:ar?'الصوت والصورة':'Audio & camera',icon:Mic},...(record.attempts.length>1?[{id:'comparison',label:ar?'قارن المحاولات':'Compare attempts',icon:Layers}]:[])];
 const withheld=WITHHELD_TRAINING_QUESTIONS.has(q.id),socialOnly=isSocialAcknowledgment(last.answer);
 if(withheld||socialOnly)return <section className="reference-assessment" aria-label={ar?'مراجعة المناقشة':'Discussion review'}><h3>{ar?'هذه الملاحظة لا تُستخدم لتقييمك':'This finding is excluded from your assessment'}</h3><p>{withheld?(ar?'أوقفنا استخدام هذا المرجع التدريبي إلى حين التحقق من نطاقه ومعاييره. الملاحظات السابقة المبنية عليه ليست دليلًا على نقص في إجابتك.':'This training reference is withheld pending verification of its scope and criteria. Earlier findings based on it are not evidence of a gap in your answer.'):(ar?'المحفوظ هنا عبارة شكر أو إقرار فقط، وليس إجابة موضوعية يمكن تقييمها. لا تُحسب النقاط غير المذكورة نقصًا في معرفتك.':'The saved response is only thanks or acknowledgment, not a substantive answer. Unmentioned points are not counted as gaps in your knowledge.')}</p><details><summary>{ar?'إجابتك الأصلية المحفوظة':'Your preserved original answer'}</summary><p dir="auto">{last.answer}</p></details></section>;
 return <section className="reference-assessment" aria-label={ar?'مراجعة المناقشة':'Discussion review'}>
  <div className="review-heading"><div><span className="eyebrow">{ar?'مراجعة المناقشة':'Discussion review'}</span><h3 ref={heading} tabIndex={-1}>{verdicts[lang][last.assessment.verdict]}</h3></div><span className="review-attempt-number">{ar?'المحاولة':'Attempt'} {record.attempts.length}</span></div>
  <div className="review-snapshot"><div className="review-coverage"><strong>{covered.toLocaleString(lang)}<small> / {last.assessment.points.length.toLocaleString(lang)}</small></strong><span>{ar?'نقاط تناولتها وفق المرجع':'Reference points addressed'}</span><div className="review-segments" aria-hidden="true">{last.assessment.points.map(p=><i key={p.id} data-status={p.status}/>)}</div></div><div className="review-next"><span className="eyebrow">{covered===last.assessment.points.length?(ar?'ثبّت ما أتقنته':'Build on your answer'):(ar?'ركّز في المحاولة التالية':'Your next practice focus')}</span><p>{q.points.find(p=>p.id===focus?.id)?.text[record.language]}</p><button className="primary" disabled={disabled} onClick={()=>onRetry(focus?.id)}>{ar?'تدرّب على هذه النقطة':'Practise this point'}<ArrowUpRight size={18}/></button></div></div>
  <details className="review-coach-note"><summary>{ar?'اقرأ خلاصة المراجعة':'Read the review summary'}</summary><p dir="auto">{last.assessment.spokenFeedback}</p>{onSpeak&&<button className="text-button" disabled={disabled} onClick={onSpeak}>{ar?'استمع للملاحظة':'Listen to feedback'}</button>}</details>
  <nav className="review-navigation" aria-label={ar?'أقسام المراجعة':'Review sections'}>{tabs.map(({id,label,icon:Icon})=><button key={id} aria-pressed={panel===id} onClick={()=>setPanel(id)}><Icon size={18}/>{label}</button>)}</nav>
  <div className="review-panel" hidden={panel!=='evidence'}>
  <div className="review-evidence-workspace">
  <div className="reference-findings" role="group" aria-label={ar?'اختر نقطة للمراجعة':'Select a review point'}>{last.assessment.points.map(p=><button key={p.id} className="reference-finding" data-status={p.status} aria-pressed={selected?.id===p.id} onClick={()=>setSelection(p.id)}><span className="finding-label">{p.status==='covered'?<Check size={18}/>:<Circle size={18}/>}<span>{q.points.find(c=>c.id===p.id)?.text[record.language]}</span></span><small>{states[lang][p.status]}</small></button>)}</div>
  {selected&&<article className="reference-point-detail">
   <h4>{criterion?.text[record.language]}</h4>
   <div className="reference-evidence-grid"><div><h5>{ar?'الدليل من إجابتك':'Evidence from your answer'}</h5>{selected.answerQuote?<>{(selected.evidence?.length?selected.evidence:[{quote:selected.answerQuote}]).map((e,i)=><blockquote dir="auto" key={i}>{e.quote}</blockquote>)}{questionTurn&&<details><summary>{ar?'السؤال الذي أجبت عنه':'The question you answered'}</summary><p dir="auto">{questionTurn.text}</p></details>}</>:<p>{ar?'لم تُحدّد عبارة من إجابتك تتناول هذه النقطة. هذا نقص في الدليل، وليس إثباتًا على اعتقادك.':'No passage addressing this point was identified in your answer. This is an evidence gap, not proof of your beliefs.'}</p>}<p dir="auto">{selected.explanation}</p></div>
   <div><h5>{ar?'المتوقع وفق المرجع':'Expected according to the reference'}</h5>{onListenReference&&<button className="secondary" disabled={disabled} onClick={onListenReference}>{referenceAudioActive?(ar?'إيقاف الصوت':'Stop audio'):(ar?'استمع للجواب المرجعي':'Listen to the reference answer')}</button>}<p dir="auto">{criterion?.text[record.language]}</p><details><summary>{ar?'الجواب المرجعي ودليله':'Reference answer and evidence'}</summary><p dir="auto">{q.answer[record.language]}</p><small>{ar?'إعادة صياغة من المرجع، وليست اقتباسًا حرفيًا. المقاطع التالية تخص السؤال كاملًا.':'Paraphrased from the reference, not a verbatim quotation. The following source passages support the question as a whole.'}</small><p>{q.source.author}</p><a href={q.source.url} target="_blank" rel="noreferrer">{q.source.title}</a>{q.evidence?.length?q.evidence.map((e,i)=><blockquote dir="auto" key={i}><small>{e.locator}</small>{e.quote}</blockquote>):<blockquote dir="auto"><small>{q.source.pages}</small>{q.source.excerpt}</blockquote>}{q.status==='draft_requires_human_review'&&<p className="scope-note">{ar?'هذا السجل مراجع آليًا وما زال يحتاج إلى مراجعة مختص؛ قد تحتوي النصوص المستخرجة من الصفحات على أخطاء.':'This record is model-reviewed and still awaits specialist review; page transcriptions may contain errors.'}</p>}</details></div></div>
  </article>}
  </div><div className="review-panel-footer"><span>{ar?'عدم ذكر نقطة لا يعني إنكارها. التقييم مقارنة بالمرجع، وليس اعتمادًا دينيًا.':'Omitting a point does not mean denying it. This is a reference comparison, not religious approval.'}</span><button className="text-button" disabled={disabled} onClick={()=>onRetry()}>{ar?'أعد الإجابة عن السؤال نفسه':'Retry the same question'}</button></div>
  </div><div className="review-panel" hidden={panel!=='recording'}>{record.attempts.length>1&&<label>{ar?'تسجيلات المحاولة':'Recordings from attempt'}<select value={mediaAttempt} onChange={e=>setMediaAttempt(Number(e.target.value))}>{record.attempts.map((a,i)=><option key={a.id} value={i+1}>{ar?'المحاولة':'Attempt'} {i+1}</option>)}</select></label>}<CallMediaReview key={mediaAttempt} sessionId={record.sessionId||''} recordId={record.id} attempt={mediaAttempt} lang={lang} onPractice={id=>onRetry(`delivery:${id}`)}/>
  {last.turns?.some(t=>t.spokenDelivery)&&<SpokenDeliveryReview onAudioRetry={id=>onRetry(`delivery:${id}`)} onRetry={()=>onRetry('delivery:pauses')} disabled={disabled} attempt={last} original={record.attempts.length>1?original:undefined} recordings={recordings} lang={lang}/>}
  </div><div className="review-panel" hidden={panel!=='quality'}><TrainingQualityReview quality={last.assessment.quality} original={record.attempts.length>1?original.assessment.quality:undefined} lang={lang} disabled={disabled} onRetry={id=>onRetry(`quality:${id}`)}/>
  </div><details className="reference-review-transcript"><summary>{ar?'مرجع التقييم وسجل المناقشة':'Assessment reference and discussion'}</summary>{last.turns?.some(t=>t.role==='assistant'&&t.delivery==='uncertain')&&<p className="scope-note">{ar?'المراجعة مبنية على إجاباتك النصية والأسئلة المعروضة؛ اكتمال سماع الصوت غير مؤكد.':'Review uses your text answers and displayed questions; complete audio playback was not confirmed.'}</p>}<a href={q.source.url} target="_blank" rel="noreferrer">{q.source.title}</a><p>{q.source.author} · {q.source.pages}</p><blockquote dir="auto">{q.source.excerpt}</blockquote>{last.turns?.map(t=><p key={t.id} dir="auto"><strong>{t.role==='user'?(ar?'أنت':'You'):(ar?'شخصية التدريب':'Practice partner')}</strong>: {t.text}</p>)}</details>
  {record.attempts.length>1&&<section className="reference-comparison review-panel" hidden={panel!=='comparison'}><h3>{ar?'المحاولات بنفس المعايير':'Attempts against the same criteria'}</h3><p>{ar?'نقارن تصنيفات التقييم والأدلة؛ لا نفترض تحسّنًا أو نحكم على قدراتك من محاولة واحدة.':'Compare assessment classifications and evidence. A retry does not automatically mean improvement or establish your ability.'}</p><label>{ar?'قارن المحاولة الأصلية مع':'Compare the original attempt with'}<select value={retry.id} onChange={e=>setComparisonId(e.target.value)}>{record.attempts.slice(1).map((a,i)=><option value={a.id} key={a.id}>{ar?'المحاولة':'Attempt'} {i+2}</option>)}</select></label>
   {compareReferenceAttempts(q,original,retry).map(row=><article className="reference-change" key={row.criterion.id}><h4>{row.criterion.text[record.language]}</h4><p>{changes[lang][row.change]}</p><div className="reference-evidence-grid">{[{attempt:original,point:row.before,label:ar?'الأصلية':'Original'},{attempt:retry,point:row.after,label:ar?'إعادة التدريب':'Retry'}].map(({attempt,point,label})=><div key={attempt.id}><strong>{label} · {point?states[lang][point.status]:'—'}</strong>{point?.answerQuote&&(point.evidence?.length?point.evidence:[{quote:point.answerQuote}]).map((e,i)=><blockquote dir="auto" key={i}>{e.quote}</blockquote>)}<p dir="auto">{point?.explanation}</p></div>)}</div></article>)}
   {retry.id!==last.id&&<SpokenDeliveryReview attempt={retry} original={original} recordings={recordings} lang={lang}/>}
   {retry.id!==last.id&&<TrainingQualityReview quality={retry.assessment.quality} original={original.assessment.quality} lang={lang} disabled={disabled} onRetry={id=>onRetry(`quality:${id}`)}/>}
   <details><summary>{ar?'نصوص المحاولات المحفوظة':'Saved attempt transcripts'}</summary><div className="answer-comparison">{record.attempts.map((a,i)=><article className="answer-attempt" key={a.id}><strong>{ar?'المحاولة':'Attempt'} {i+1}</strong><blockquote dir="auto">{a.answer}</blockquote>{a.turns&&<details><summary>{ar?'المناقشة الكاملة':'Full discussion'}</summary>{a.turns.map(t=><p dir="auto" key={t.id}>{t.role==='user'?(ar?'أنت':'You'):(ar?'شخصية التدريب':'Practice partner')}: {t.text}</p>)}</details>}</article>)}</div></details>
  </section>}
 </section>;
}
