import {AUDIO_CRITERIA,type AudioCriterion} from './audioAssessment';
import {useRef,useState} from 'react';
import type {Lang} from './content';
import type {ReferenceAttempt} from './referencePracticeTypes';
import type {SpokenDelivery} from './spokenDelivery';
function RecordingObservation({m,url,lang,index,onAudioRetry,disabled}:{onAudioRetry?:(id:AudioCriterion)=>void;disabled?:boolean;m:SpokenDelivery;url?:string;lang:Lang;index:number}){
 const [playError,setPlayError]=useState(false),stopAt=useRef<number|null>(null);
 const ar=lang==='ar',player=useRef<HTMLAudioElement>(null),fmt=(n:number)=>n.toLocaleString(lang,{maximumFractionDigits:1});
 return <article className="quality-finding"><h5>{ar?'تسجيل الإجابة':'Answer recording'} {index+1}</h5>
 {m.assessment&&<div className="audio-coaching"><h5>{ar?'مراجعة الأداء من الصوت':'Coaching from your recording'}</h5><p className="scope-note">{ar?'ملاحظات آلية قابلة للخطأ، وليست اختبارًا معتمدًا للنطق. الأوقات تحدد مقاطع التسجيل الداعمة، وليست توقيت الكلمات. لا نقيّم اللهجة أو الثقة أو المشاعر.':'AI listening observations can be wrong and are not a certified pronunciation test. Times identify supporting recording segments, not word timings. Accent, confidence and emotions are not graded.'}</p>
 {m.assessment.findings.map(f=><details className="quality-finding" key={f.criterion} open={f.status==='practice'}><summary><span>{AUDIO_CRITERIA[f.criterion][lang]}</span><small>{f.status==='effective'?(ar?'نقطة قوة مسموعة':'Audible strength'):f.status==='practice'?(ar?'اقتراح للتدريب':'Practice suggestion'):(ar?'لا تكفي الأدلة':'Insufficient evidence')}</small></summary><p dir="auto">{f.observation}</p>{f.segments.map(g=><button key={g.id} className="text-button" disabled={!url} onClick={()=>{if(player.current){setPlayError(false);stopAt.current=g.end;player.current.currentTime=g.start;void player.current.play().catch(()=>setPlayError(true));}}}>{ar?'استمع للمقطع':'Listen to segment'} {fmt(g.start)}–{fmt(g.end)} {ar?'ثانية':'s'}</button>)}{f.suggestion&&<p dir="auto">{f.suggestion}</p>}{f.status==='practice'&&onAudioRetry&&<button className="secondary" disabled={disabled} onClick={()=>onAudioRetry(f.criterion)}>{ar?'تدرّب على هذا الجانب الصوتي':'Practise this delivery point'}</button>}</details>)}
 </div>}
 {m.assessmentError&&<p role="status">{ar?'لم تكتمل المراجعة الصوتية لهذا التسجيل؛ لم نعرض نتائج بديلة. أعد التسجيل للمحاولة مجددًا.':'Audio review did not complete for this recording; no substitute findings were generated. Record again to retry.'}</p>}
 <details open={m.assessment?undefined:true}><summary>{ar?'قياسات التسجيل التقريبية':'Approximate recording measurements'}</summary>
 {m.status!=='measured'?<p>{ar?'لا تكفي جودة الإشارة أو مدتها للقياس. لم نمنح تقييمًا للأداء.':'The signal or duration is insufficient for measurement. No delivery rating was assigned.'}</p>:<>
 <p>{ar?'مدة التسجيل':'Recording duration'}: {fmt(m.duration)} {ar?'ثانية':'seconds'}. {m.wordsPerMinute!==null&&!m.transcriptEdited?<>{ar?'المعدل التقريبي':'Approximate rate'}: {fmt(m.wordsPerMinute)} {ar?'كلمة/دقيقة':'words/minute'}.</>:<>{ar?'لا يتوفر تقدير موثوق للمعدل من هذا المقطع.':'A reliable rate estimate is unavailable for this clip.'}</>}</p>
 <p>{ar?'فترات انخفاض الصوت الداخلية (٠٫٨ ثانية أو أكثر)':'Internal low-volume intervals (0.8 seconds or longer)'}: {m.gaps.length}</p>
 {m.gaps.length>0&&<p>{ar?'استمع قبل الموضع وبعده، ثم قرّر: هل تخدم الوقفة المعنى أم تقطع الفكرة؟ إذا قطعتها، جرّب إكمال الفكرة في جملة قصيرة ثم توقّف.':'Listen before and after the interval. Does the pause support the meaning or interrupt the idea? If it interrupts, try completing one short thought before pausing.'}</p>}
 {m.gaps.map((g,i)=><button key={i} className="text-button" disabled={!url} onClick={()=>{if(player.current){setPlayError(false);stopAt.current=Math.min(m.duration,g.end+1.5);player.current.currentTime=Math.max(0,g.start-1.5);void player.current.play().catch(()=>setPlayError(true));}}}>{ar?'استمع حول':'Listen around'} {fmt(g.start)}–{fmt(g.end)} {ar?'ثانية':'s'}</button>)}
 {!m.transcriptEdited&&<p>{ar?'ألفاظ تردّد محتملة ظهرت في التفريغ':'Possible filler tokens present in the transcript'}: {m.fillers.length?m.fillers.map(f=>`${f.token} (${f.count})`).join(' · '):ar?'لم يرصد التفريغ ألفاظًا من القائمة المحدودة.':'The transcript contains none from the limited list.'}</p>}
 {m.transcriptEdited&&<p>{ar?'عُدّل النص بعد التسجيل؛ أُخفي معدل الكلمات وألفاظ التردّد كي لا ننسب كلمات مكتوبة إلى الصوت.':'The transcript was edited after recording; word rate and filler observations are hidden to avoid attributing edited words to the recording.'}</p>}
 </>}
 </details>
 {url?<audio ref={player} onTimeUpdate={()=>{if(player.current&&stopAt.current!==null&&player.current.currentTime>=stopAt.current){player.current.pause();stopAt.current=null;}}} onPause={()=>{stopAt.current=null;}} onError={()=>setPlayError(true)} controls preload="metadata" src={url} aria-label={ar?'استمع إلى إجابتك':'Listen to your answer'}/>:<p className="scope-note">{ar?'التسجيل غير متاح في ذاكرة هذه الصفحة؛ القياسات فقط محفوظة.':'Recording unavailable in this page’s memory; only measurements are saved.'}</p>}
 {playError&&<p role="status">{ar?'تعذّر تشغيل التسجيل. جرّب زر التشغيل أو سجّل محاولة جديدة.':'Recording playback failed. Try the player controls or record a new attempt.'}</p>}
 </article>;
}
export function SpokenDeliveryReview({attempt,original,recordings={},lang,onRetry,onAudioRetry,disabled=false}:{onAudioRetry?:(id:AudioCriterion)=>void;onRetry?:()=>void;disabled?:boolean;attempt:ReferenceAttempt;original?:ReferenceAttempt;recordings?:Record<string,string>;lang:Lang}){
 const ar=lang==='ar',measures=attempt.turns?.flatMap(t=>t.role==='user'&&t.spokenDelivery?[t.spokenDelivery]:[])||[],before=original?.turns?.flatMap(t=>t.role==='user'&&t.spokenDelivery?[t.spokenDelivery]:[])||[];
 return <section className="training-quality" aria-label={ar?'ملاحظات التسجيل الصوتي':'Recording delivery observations'}><h4>{ar?'ملاحظات التسجيل الصوتي':'Recording delivery observations'}</h4>
 {!measures.length?<p>{ar?'لا يوجد تسجيل مقاس لهذه المحاولة. لا نستنتج الأداء الصوتي من النص.':'No measured recording is available for this attempt. Spoken delivery is not inferred from text.'}</p>:<><p className="scope-note">{measures.some(m=>m.assessment)?(ar?'استمع إلى الدليل الصوتي وجرّب اقتراحًا واحدًا في كل إعادة. تبقى مراجعة صحة الإجابة منفصلة.':'Listen to the audio evidence and try one suggestion per retry. Answer correctness is reviewed separately.'):ar?'قياسات تقريبية من التسجيل في متصفحك، وليست درجات جودة. الضوضاء وخفوت الصوت يؤثران في الكشف، وانخفاض الصوت ليس دائمًا وقفة كلام. المعدل يعتمد على التفريغ وقد لا يحفظ كل ألفاظ التردّد. لا يوجد معدل مثالي للجميع، هذه القياسات وحدها لا تقيّم النطق أو التنغيم.':'Approximate browser measurements, not quality scores. Noise and quiet speech affect detection; low volume is not always a speech pause. Rate depends on transcription, which may omit fillers. There is no universal ideal rate. These measurements alone do not assess pronunciation or intonation.'}</p>
 {measures.map((m,i)=><RecordingObservation key={m.recordingId} m={m} url={recordings[m.recordingId]} lang={lang} index={i} onAudioRetry={onAudioRetry} disabled={disabled}/>)}
 <p>{ar?'جرّب الاستماع إلى المواضع المحددة: هل تساعد الوقفة على توضيح الفكرة؟ في الإعادة، جرّب جملة واحدة واضحة دون محاولة الإسراع لمجرد رفع المعدل.':'Listen to the marked intervals: does the pause help explain the idea? On retry, try one clear sentence without speeding up merely to raise the rate.'}</p>
 {onRetry&&<button className="secondary" disabled={disabled} onClick={onRetry}>{ar?'أعد التسجيل مع التركيز على الوقفات':'Record a retry focused on pauses'}</button>}
 {original&&before.length===1&&measures.length===1&&before[0].status==='measured'&&measures[0].status==='measured'&&<div className="delivery-comparison"><h5>{ar?'المحاولتان جنبًا إلى جنب':'Both attempts side by side'}</h5><table><thead><tr><th>{ar?'الملاحظة':'Observation'}</th><th>{ar?'الأصلية':'Original'}</th><th>{ar?'الإعادة':'Retry'}</th></tr></thead><tbody><tr><th>{ar?'مدة التسجيل (ثانية)':'Duration (seconds)'}</th>{[before[0],measures[0]].map((m,i)=><td key={i}>{m.duration.toLocaleString(lang,{maximumFractionDigits:1})}</td>)}</tr><tr><th>{ar?'فترات انخفاض الصوت':'Low-volume intervals'}</th>{[before[0],measures[0]].map((m,i)=><td key={i}>{m.gaps.length.toLocaleString(lang)}</td>)}</tr></tbody></table><p>{ar?'الأقل ليس أفضل بالضرورة. استمع إلى التسجيلين: أيهما يمنح الفكرة وقتها دون أن يقطعها؟':'Fewer is not necessarily better. Listen to both: which gives the idea room without interrupting it?'}</p></div>}
 {original&&before.length===1&&measures.length===1&&before[0].assessment&&measures[0].assessment&&<div className="delivery-comparison"><h5>{ar?'مقارنة الملاحظات الصوتية':'Compare audio observations'}</h5><p>{ar?'استمع إلى التسجيلين قبل الحكم على التحسّن. اختلاف الظروف أو النص قد يغيّر الملاحظة.':'Listen to both recordings before judging improvement. Different recording conditions or wording may change the observation.'}</p>{(Object.keys(AUDIO_CRITERIA) as AudioCriterion[]).map(id=><details key={id}><summary>{AUDIO_CRITERIA[id][lang]}</summary><p><strong>{ar?'الأصلية: ':'Original: '}</strong>{before[0].assessment?.findings.find(f=>f.criterion===id)?.observation}</p><p><strong>{ar?'الإعادة: ':'Retry: '}</strong>{measures[0].assessment?.findings.find(f=>f.criterion===id)?.observation}</p></details>)}</div>}
 {original&&<details><summary>{ar?'قياسات المحاولة الأصلية للمقارنة':'Original attempt measurements for comparison'}</summary><p>{ar?'تغيّر الأرقام لا يعني تحسّنًا؛ تختلف صعوبة الإجابة وطولها وظروف التسجيل.':'Different numbers do not imply improvement; answer length, difficulty and recording conditions can differ.'}</p>{before.length?before.map((m,i)=><RecordingObservation key={m.recordingId} m={m} url={recordings[m.recordingId]} lang={lang} index={i}/>):<p>{ar?'لا يوجد قياس أصلي للمقارنة.':'No original measurement is available.'}</p>}</details>}</>}
 </section>;
}
