import {enterMeeting} from './meetingTransition';
import {AUDIO_CRITERIA,type AudioCriterion} from './audioAssessment';
import {saveReviewClip,deleteSessionMedia} from './callReviewMedia';
import {callSounds} from './callSounds';
import {QUALITY_CRITERIA} from './trainingQuality';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,BookOpen,Globe2,Mic,MicOff,Video,MessageCircle,RotateCcw} from 'lucide-react';
import type {Lang,Turn} from './content';
import type {Config} from './useJourney';
import {api,RequestError,speech} from './api';
import {Microphone,PcmPlayer} from './audio';
import {errorMessage} from './experienceCopy';
import {traditionLabels,type Tradition} from './referencePracticeTypes';
import {awaitingContinuation,currentTrainingRecord,type TrainingSession} from './trainingSession';
import {ReferenceReview} from './ReferenceReview';
const VideoCall=React.lazy(()=>import('./VideoCall').then(m=>({default:m.VideoCall})));
const KEY='basira.training-meetings.v1';
type Saved={contentPractice?:boolean;token:string;id:string;language:Lang;tradition:Tradition;at:number};
export function TrainingMeeting({lang,config,onActive,practice}:{lang:Lang;config:Config|null;onActive:(active:boolean)=>void;practice?:{token:string;question:string;language:Lang}}){
 const ar=lang==='ar';
 const [reviewCapture,setReviewCapture]=useState(()=>{try{return localStorage.getItem('basira.review-recording')!=='off';}catch{return true;}});
 useEffect(()=>{try{localStorage.setItem('basira.review-recording',reviewCapture?'on':'off');}catch{/* Recording still works without preference storage. */}},[reviewCapture]);
 const [captureWarning,setCaptureWarning]=useState(false);
 const [referenceAudio,setReferenceAudio]=useState(false),referenceAudioRequest=useRef<AbortController|null>(null);
 function stopReferenceAudio(){referenceAudioRequest.current?.abort();referenceAudioRequest.current=null;player.current.stop();setReferenceAudio(false);}
 async function listenReference(){if(referenceAudio){stopReferenceAudio();return;}if(!reviewed||!session)return;const c=new AbortController();referenceAudioRequest.current=c;setReferenceAudio(true);try{const pcm=await speech(reviewed.question.answer[session.language],session.language,c.signal,session.id);if(!c.signal.aborted)await player.current.play(pcm,()=>{});}catch(e){if(!c.signal.aborted)fail(e);}finally{if(referenceAudioRequest.current===c){referenceAudioRequest.current=null;setReferenceAudio(false);}}}

 const storageKey=KEY+':'+(config?.training?.scope||'legacy');
 const [language,setLanguage]=useState<Lang>(practice?.language||lang),[tradition,setTradition]=useState<Tradition>('hinduism'),[camera,setCamera]=useState(true),[textOnly,setTextOnly]=useState(false);
 const [session,setSession]=useState<TrainingSession|null>(null),[token,setToken]=useState(''),[saved,setSaved]=useState<Saved[]>([]),[hasLegacy,setHasLegacy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[storageError,setStorageError]=useState(false),[call,setCall]=useState(false),[callKey,setCallKey]=useState(0),[input,setInput]=useState(''),[recording,setRecording]=useState(false),[voice,setVoice]=useState(false),[reviewId,setReviewId]=useState(''),[reviewing,setReviewing]=useState(false);
 const lock=useRef(false),mounted=useRef(true),request=useRef<AbortController|null>(null),mic=useRef(new Microphone()),player=useRef(new PcmPlayer()),log=useRef<HTMLDivElement>(null),follow=useRef(true),latest=useRef(session);latest.current=session;
 const current=session?currentTrainingRecord(session):null;
 const avatarReady=!!config?.training?.avatarConfigured;
 const active=!!session&&!session.ended;
 useEffect(()=>{onActive(active||call);},[active,call]);
 useEffect(()=>{try{setHasLegacy(['basira.sessions.v1','basira.reference-practice.v1'].some(key=>JSON.parse(localStorage.getItem(key)||'[]').length>0));const data=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(data))setSaved(data);}catch{setStorageError(true);}return()=>{mounted.current=false;request.current?.abort();referenceAudioRequest.current?.abort();mic.current.cancel();void player.current.close();};},[]);
 useEffect(()=>{if(follow.current&&log.current)log.current.scrollTop=log.current.scrollHeight;},[session?.revision]);
 function fail(e:unknown){if(mounted.current)setError(e instanceof RequestError?e.code:'connection_failed');}
 function remember(t:string,s:TrainingSession){try{const all=JSON.parse(localStorage.getItem(storageKey)||'[]') as Saved[];const next=[{token:t,id:s.id,language:s.language,tradition:s.tradition,contentPractice:!!s.contentOrigin,at:s.createdAt},...all.filter(v=>v.id!==s.id)];localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);}catch{setStorageError(true);}}
 async function refresh(){if(!token)return;try{const next=await api<TrainingSession>('/api/training/session/read',{token});if(mounted.current)setSession(prev=>!prev||next.revision>=prev.revision?next:prev);}catch(e){fail(e);}}
 useEffect(()=>{if(!call)return;let stopped=false;const tick=async()=>{await refresh();if(!stopped)timer=setTimeout(tick,1800);};let timer=setTimeout(tick,1000);return()=>{stopped=true;clearTimeout(timer);};},[call,token]);
 async function start(){callSounds.unlock();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const result=await api<{token:string;session:TrainingSession}>(practice?'/api/content/practice':'/api/training/session',practice?{ticket:practice.token}:{language,tradition});await enterMeeting(()=>{setToken(result.token);setSession(result.session);remember(result.token,result.session);setCall(!textOnly&&avatarReady);setCallKey(k=>k+1);});}catch(e){fail(e);}finally{lock.current=false;setBusy(false);}}
 async function action(action:string,extra:Record<string,unknown>={},speakReply=true){if(lock.current)return;stopReferenceAudio();lock.current=true;setBusy(true);if(action==='finish')setReviewing(true);setError('');player.current.stop();const controller=new AbortController();request.current=controller;try{if(!call&&latest.current?.live)await api('/api/training/video-stop',{token});const result=await api<{session:TrainingSession;text:string}>('/api/training/session/action',{token,id:crypto.randomUUID(),action,...extra},controller.signal,120000);if(!mounted.current)return;setSession(result.session);if(action==='retry'){setCall(false);setInput('');window.scrollTo({top:0,behavior:'smooth'});}if(action==='answer'||action==='finish')setInput('');if(result.session.ended)setReviewId(result.session.records.find(r=>r.id===result.session.currentId&&r.attempts.length)?.id||result.session.records.find(r=>r.attempts.length)?.id||'');if(voice&&speakReply&&result.text){const pcm=await speech(result.text,result.session.language,controller.signal,result.session.id);await player.current.play(pcm,()=>{});}return result;}catch(e){fail(e);await refresh();}finally{lock.current=false;setBusy(false);setReviewing(false);}}
 async function toggleMic(){if(recording){setRecording(false);setBusy(true);lock.current=true;const controller=new AbortController();request.current=controller;try{const blob=await mic.current.finish();if(reviewCapture&&session&&current){try{await saveReviewClip({id:crypto.randomUUID(),sessionId:session.id,recordId:current.id,attempt:current.attempts.length+1,at:Date.now(),duration:0,blob,frames:[]});setCaptureWarning(false);}catch{setCaptureWarning(true);}}const r=await fetch(`/api/transcribe?language=${session!.language}`,{method:'POST',headers:{'Content-Type':blob.type,'X-Basira-Session':session!.id},body:blob,signal:AbortSignal.any([controller.signal,AbortSignal.timeout(60000)])});const data=await r.json();if(!r.ok)throw new RequestError(data.error);if(!mounted.current||controller.signal.aborted)return;setInput(data.text);lock.current=false;setBusy(false);await action('answer',{text:data.text,inputKind:'transcribed'});}catch(e){fail(e);}finally{lock.current=false;setBusy(false);}return;}player.current.stop();try{if(latest.current?.live)await api('/api/training/video-stop',{token});await mic.current.start(()=>{mic.current.cancel();setRecording(false);setError('recording_limit');});setRecording(true);}catch{setError('microphone_unavailable');}}
 async function reconnect(){callSounds.unlock();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await api('/api/training/video-stop',{token});let next=await api<TrainingSession>('/api/training/session/read',{token});if(next.error||(currentTrainingRecord(next).turns?.at(-1)?.role==='user'&&!awaitingContinuation(next))){next=(await api<{session:TrainingSession}>('/api/training/session/action',{token,id:crypto.randomUUID(),action:'recover'},undefined,120000)).session;}setSession(next);if(!next.ended){setCallKey(k=>k+1);setCall(true);}else setCall(false);}catch(e){fail(e);}finally{lock.current=false;setBusy(false);}}
 async function review(finalDraft?:string){if(lock.current)return;setReviewing(true);setCall(false);await refresh();await action('finish',{text:finalDraft,inputKind:'typed'},false);}
 const renderedTurns=React.useMemo<Turn[]>(()=>session?(current?.retrying?[current]:session.records).flatMap(r=>(r.turns||[]).map(t=>({id:t.id,role:t.role,text:t.text,at:session.createdAt,delivery:t.delivery==='text'?'text':'uncertain'}))):[],[session?.revision,session?.id]);
 const reviewed=session?.records.find(r=>r.id===reviewId&&r.attempts.length)||session?.records.find(r=>r.attempts.length);
 function message(code:string){const messages:Record<string,[string,string]>={local_recording_delete_failed:['حُذف سجل التدريب، لكن تعذّر حذف التسجيلات من هذا الجهاز. احذف بيانات هذا الموقع من إعدادات المتصفح لإزالتها.','The training record was deleted, but local recordings could not be removed. Clear this site’s data in browser settings to remove them.'],invalid_model_evidence:['إجابتك محفوظة. تعذّر التحقق من الخطوة التالية؛ أعد الاتصال لاستكمالها، أو تابع من الإجابة المحفوظة.','Your answer is saved. We could not verify the next step. Reconnect to resume, or continue from your saved answer.'],training_avatar_not_configured:['الاتصال بالتدريب الصوتي غير مهيّأ بعد. يمكنك متابعة التدريب بالكتابة.','Source-guided avatar connection is not configured yet. You can train by text.'],training_busy:['جارٍ حفظ إجابتك ومراجعتها. حاول بعد لحظات.','Your answer is being saved and reviewed. Try again shortly.'],training_pending:['إجابتك محفوظة. أكمل معالجة الإجابة قبل إعادة الاتصال.','Your answer is saved. Resume its processing before reconnecting.'],training_end_first:['أنه اتصال الشخصية أولًا قبل تغيير المحاولة.','End the avatar connection before changing the attempt.'],training_storage_unavailable:['تعذّر الوصول إلى سجل التدريب. حاول مجددًا.','Training records are unavailable. Please retry.'],training_session_missing:['هذا السجل غير متاح أو انتهت مدة حفظه.','This record is unavailable or its retention period has ended.']};return messages[code]?.[ar?0:1]||errorMessage(code,lang);}
 const reportView=reviewing||!!session?.ended&&!call;
 useEffect(()=>{if(reportView){window.scrollTo({top:0,behavior:'smooth'});document.getElementById('training-report-title')?.focus();}},[reportView]);
 return <section className={`grounded-meeting ${call?'is-calling':''} ${current?.retrying&&!call&&!reportView?'is-retry-ready':''} ${reportView?'is-report':''} ${!session?'is-preparing':''}`} aria-busy={reviewing}>
 {reportView&&<header className="training-report-header"><h1 id="training-report-title" tabIndex={-1}>{reviewing?(ar?'جارٍ إعداد مراجعتك':'Preparing your review'):(ar?'مراجعة التدريب':'Training review')}</h1><span>{ar?'من إجابتك إلى محاولتك التالية':'From your answer to your next attempt'}</span></header>}
 {reviewing&&<div className="training-review-loading" role="status"><div className="review-orbit"><BookOpen size={32}/></div><h2>{ar?'نربط إجاباتك بالمراجع':'Connecting your answers with the references'}</h2><p>{ar?'نراجع سياق الحوار والأدلة قبل عرض الملاحظات. قد يستغرق ذلك بعض الوقت.':'We’re checking the conversation and its evidence before presenting feedback. This may take a little time.'}</p><span>{ar?'كلماتك محفوظة':'Your words are saved'}</span></div>}
 {!reportView&&<>
 {current?.retrying&&!call&&<div className="reference-focus" role="status"><strong>{ar?'محاولتك التالية جاهزة':'Your next attempt is ready'}</strong><p>{ar?'إجابتك الأولى ومراجعتها محفوظتان. راجع السؤال ونقطة التركيز، ثم أجب بالكتابة أو سجّل إجابتك صوتيًا للمقارنة.':'Your original answer and review are saved. Check the question and focus, then type or record your answer for comparison.'}</p></div>}
 {current?.focusAudioCriterion&&<p className="reference-focus">{ar?'ركّز في هذه المحاولة على: ':'For this retry, focus on: '}{AUDIO_CRITERIA[current.focusAudioCriterion][lang]}</p>}
 <div className="page-intro"><div><div className="eyebrow">{ar?'مساحة للحوار':'Space for dialogue'}</div><h1>{ar?'حوارٌ ينمو معك':'A conversation to grow through'}</h1><p>{ar?'اختر سياق الحوار، أنصت، ثم عبّر عن فكرتك.':'Choose a conversation context, listen, then share your perspective.'}</p></div></div>
 {call&&session&&<div className="meeting-context-bar"><span><BookOpen size={16}/>{session.contentOrigin?(ar?'تدرّب على المحتوى':'Content practice'):traditionLabels[session.tradition][lang]}</span><span>{session.language==='ar'?'العربية':'English'}</span><span>{ar?'أسئلة نوقشت':'Questions discussed'} · {session.records.filter(r=>r.attempts.length).length}</span>{current?.retrying&&<span>{ar?'محاولة جديدة':'Targeted retry'}</span>}</div>}
 <div className="workspace">{!current?.retrying&&<aside className="sidebar"><div className="scenario"><BookOpen size={20}/><h2>{ar?'من الحوار إلى التأمّل':'From dialogue to reflection'}</h2><p>{ar?'لكل سؤال مرجع، ولكل محاولة مساحة جديدة.':'A reference behind each question. A fresh opportunity with each attempt.'}</p></div>
 <div className="settings">{practice||session?.contentOrigin?<div className="practice-question"><strong>{ar?'تدرّب على نقطة من المحتوى':'Practise a content-review point'}</strong><p dir="auto">{session?.contentOrigin?.passage||practice?.question}</p></div>:<><label htmlFor="training-context">{ar?'سياق الحوار':'Dialogue context'}</label><div className="session-language-field"><BookOpen size={17}/><select id="training-context" value={session?.tradition||tradition} disabled={!!session} onChange={e=>setTradition(e.target.value as Tradition)}>{Object.entries(traditionLabels).map(([key,label])=><option key={key} value={key}>{label[lang]}</option>)}</select></div></>}
 <label htmlFor="session-language">{ar?'لغة الحوار':'Conversation language'}</label><div className="session-language-field"><Globe2 size={17}/><select id="session-language" value={session?.language||language} disabled={!!session||!!practice} onChange={e=>setLanguage(e.target.value as Lang)}><option value="ar">العربية</option><option value="en">English</option></select></div>
 <p className="scope-note">{textOnly?(ar?'حوار كتابي دون تشغيل الكاميرا أو الميكروفون.':'Text conversation without camera or microphone.'):camera?(ar?'تبدأ المكالمة بالكاميرا والميكروفون بعد إذنك. يمكنك إيقافهما أثناء الحوار.':'The call starts with camera and microphone after permission. You can turn either off during the conversation.'):(ar?'تبدأ المكالمة بالميكروفون بعد إذنك. يمكنك تشغيل الكاميرا أثناء الحوار.':'The call starts with your microphone after permission. You can turn on the camera during the conversation.')}</p>
 {!session&&<button className="primary start-button" disabled={busy||!config?.ai.configured} onClick={()=>void start()}>{busy?(ar?'جارٍ التحضير…':'Preparing…'):textOnly?(ar?'ابدأ الحوار الكتابي':'Begin text conversation'):(ar?'ابدأ الحوار':'Begin conversation')}</button>}
 <details className="meeting-details"><summary>{ar?'إعدادات الحوار':'Conversation settings'}</summary>
 {!session&&<><button type="button" className="text-button" aria-pressed={camera} disabled={textOnly} onClick={()=>setCamera(!camera)}>{camera?(ar?'الكاميرا عند البدء: مفعّلة':'Start camera: on'):(ar?'الكاميرا عند البدء: متوقفة':'Start camera: off')}</button><button type="button" className="studio-mode-link" aria-pressed={textOnly} onClick={()=>setTextOnly(!textOnly)}><MessageCircle size={17}/>{textOnly?(ar?'استخدام الشخصية':'Use the avatar'):(ar?'استخدام الحوار الكتابي':'Use text conversation')}</button></>}
 <button type="button" className="text-button" aria-pressed={reviewCapture} onClick={()=>setReviewCapture(!reviewCapture)}>{reviewCapture?(ar?'إيقاف حفظ التسجيل للمراجعة':'Turn off review recording'):(ar?'تفعيل حفظ التسجيل للمراجعة':'Turn on review recording')}</button>
 <p className="scope-note">{ar?'تُحفظ المقاطع على جهازك وبمساحة خاصة حتى ٧ أيام وتُرسل للتحليل. يمكنك إيقاف الحفظ وحذف التسجيلات من التقرير.':'Clips are saved on your device and in private storage for up to 7 days and sent for analysis. You can stop saving and delete recordings from the report.'}</p></details>
 <p className="scope-note" role="status">{textOnly?'':reviewCapture?(ar?'حفظ التسجيل لمراجعة الأداء مفعّل':'Recording for delivery review is on'):(ar?'حفظ التسجيل للمراجعة متوقف':'Review recording is off')}</p>
 {!session&&!avatarReady&&!textOnly&&<p role="status" className="mode-note">{message('training_avatar_not_configured')}</p>}

 {session&&<><p className="mode-note">{ar?'أسئلة نوقشت':'Questions discussed'}: {session.records.filter(r=>r.attempts.length).length}</p>{!call&&!session.ended&&avatarReady&&<button className="secondary" disabled={busy||recording||!!session.error} onClick={async()=>{callSounds.unlock();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(session.live)await api('/api/training/video-stop',{token});setTextOnly(false);setCallKey(k=>k+1);setCall(true);}catch(e){fail(e);}finally{lock.current=false;setBusy(false);}}}><Video size={16}/>{ar?'الاتصال بالشخصية':'Connect avatar'}</button>}{!call&&session.ended&&<button className="secondary" onClick={()=>{stopReferenceAudio();setSession(null);setToken('');setReviewId('');}}>{ar?'حوار جديد':'New conversation'}</button>}</>}
 </div><p className="mode-note">{practice||session?.contentOrigin?(ar?'تدرّب على مناقشة التصحيح مع كاتب افتراضي باحترام. تقتصر المراجعة على الاقتباس والمرجع المحدد، وليست اعتمادًا دينيًا.':'Practise discussing the correction respectfully with a simulated author. Review is limited to the quotation and selected reference; it is not religious approval.'):(ar?'الشخصية محاكاة للتدريب، ولا تمثل جميع أتباع الخلفية المختارة. نقارن إجابتك بالمرجع المحدد، دون إصدار اعتماد ديني.':'The simulated partner does not represent everyone from this background. Review compares your answer with the selected source; it is not religious approval.')}</p></aside>}
 <section className="conversation-space" aria-label={ar?'الحوار':'Conversation'}>{session&&current?.retrying&&<p className="reference-focus">{ar?'تركيز المحاولة: ':'Practice focus: '}{current.focusQualityId?QUALITY_CRITERIA[current.focusQualityId][lang]:current.question.points.find(p=>p.id===current.focusPointId)?.text[session.language]||(ar?'أعد الإجابة؛ توضيح واحد عند الحاجة، ثم نفتح مقارنة المحاولتين.':'Answer again; one clarification if needed, then we open your comparison.')}</p>}{call&&session?<React.Suspense fallback={<div className="inline-call-loading meeting-loading-shell" role="status"><span className="meeting-arrival-orbit" aria-hidden="true"/>{ar?'جارٍ تجهيز الاتصال…':'Preparing the call…'}</div>}><VideoCall onReviewCaptureChange={setReviewCapture} reviewCapture={reviewCapture} captureContext={current?{sessionId:session.id,recordId:current.id,attempt:current.attempts.length+(current.completed?0:1)}:undefined} waitingForContinuation={!!session&&awaitingContinuation(session)} key={callKey} trainingToken={token} trainingEnded={session.ended} trainingError={session.error} trainingTurns={renderedTurns} initialSessionId={session.id} onTrainingUpdate={()=>void refresh()} lang={lang} language={session.language} initialCamera={camera} autoStart embedded onRestart={()=>reconnect()} onContinueText={async()=>{setTextOnly(true);setCall(false);await refresh();}} onBack={()=>{setCall(false);void refresh();}} onReview={(_id,_turns,draft)=>review(draft)}/></React.Suspense>:<>
 <div className="stage grounded-stage"><div className="stage-top"><span>{ar?'بصيرة · شخصية تدريب افتراضية':'Basira · Simulated practice partner'}</span><span>{session?(ar?'حوار موثّق':'Source-guided dialogue'):'BASIRA'}</span></div><div className="stage-center"><BookOpen size={38}/><h2>{session?.ended?(ar?'مساحة للتأمّل':'Time to reflect'):session?(ar?'نستمع إلى فكرتك':'Your perspective matters'):(ar?'يبدأ الحوار بالإنصات':'Dialogue begins with listening')}</h2><p>{session?.ended?(ar?'راجع كلماتك، ثم جرّب مرة أخرى.':'Revisit your words, then try again.'):(ar?'صوتك أو كلماتك، في مساحة واحدة.':'Your voice or your words, in one space.')}</p></div></div>
 {session&&<div className="chat"><div ref={log} className="transcript" role="log" aria-label={ar?'سجل المناقشة':'Discussion history'} onScroll={()=>{const el=log.current;if(el)follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<60;}}>{renderedTurns.map(t=><div className={`turn ${t.role}`} key={t.id}><div><strong>{t.role==='user'?(ar?'أنت':'You'):(ar?'شخصية التدريب':'Practice partner')}</strong><p dir="auto">{t.text}</p></div></div>)}</div>{!session.ended&&<><form className="composer" onSubmit={e=>{e.preventDefault();void action('answer',{text:input,inputKind:'typed'});}}><input aria-label={ar?'اكتب إجابتك':'Type your answer'} value={input} dir="auto" maxLength={2400} onChange={e=>setInput(e.target.value)} disabled={busy||recording||(current?.turns?.at(-1)?.role==='user'&&!awaitingContinuation(session))}/><button aria-label={ar?'إرسال':'Send'} disabled={busy||recording||!input.trim()||(current?.turns?.at(-1)?.role==='user'&&!awaitingContinuation(session))}><ArrowUp size={19}/></button></form><div className="conversation-controls"><div>{config?.voice.transcriptionConfigured&&<button className="text-button" disabled={busy} onClick={()=>void toggleMic()}>{recording?<Mic/>:<MicOff/>}{recording?(ar?'أوقف التسجيل وأرسل':'Stop recording & send'):(ar?'سجّل إجابتك':'Record answer')}</button>}{config?.voice.configured&&<label><input type="checkbox" checked={voice} onChange={e=>{setVoice(e.target.checked);if(!e.target.checked)player.current.stop();}}/>{ar?'استمع للرد':'Spoken replies'}</label>}</div><button className="primary end-review-action" disabled={busy||recording} onClick={()=>void action('finish',{text:input.trim()||undefined,inputKind:'typed'},false)}>{input.trim()?(ar?'إرسال الإجابة وإنهاء التدريب ومراجعته':'Submit answer, end training & review'):(ar?'إنهاء التدريب ومراجعته':'End training & review')}</button></div></>}{busy&&<p role="status">{ar?'جارٍ التفكير في إجابتك…':'Considering your answer…'}</p>}</div>}
 </>}</section></div></>}
 {(error||session?.error)&&<div className="review-error" role="alert"><p>{message(error||session!.error!)}</p>{!call&&session&&!session.ended&&<button className="secondary" disabled={busy} onClick={()=>void action('recover')}><RotateCcw size={16}/>{ar?'أكمل من الإجابة المحفوظة':'Resume from the saved answer'}</button>}</div>}
 {reportView&&!reviewing&&session?.ended&&reviewed&&<div className="training-report-body"><div className="training-report-overview"><span className="review-count">{ar?'أسئلة تمت مراجعتها':'Questions reviewed'} <strong>{session.records.filter(r=>r.attempts.length).length}</strong></span><span className="review-count">{ar?'محاولات محفوظة':'Saved attempts'} <strong>{session.records.reduce((n,r)=>n+r.attempts.length,0)}</strong></span><span>{ar?'الخطوة التالية: اختر نقطة وأعد التدريب':'Next: choose a point and practise again'}</span></div><div className="reference-selectors">{session.records.filter(r=>r.attempts.length).length===1?<p className="review-question" dir="auto">{reviewed.question.question[session.language]}</p>:<details className="review-question-picker"><summary><span className="eyebrow">{ar?'أسئلة الحوار':'Conversation questions'}</span><span dir="auto">{reviewed.question.question[session.language]}</span><span className="question-picker-hint">{ar?'تغيير السؤال':'Change question'}</span></summary><div className="review-question-list" aria-label={ar?'اختر سؤالًا للمراجعة':'Choose a question to review'}>{session.records.filter(r=>r.attempts.length).map((r,i)=><button type="button" key={r.id} aria-pressed={r.id===reviewed.id} onClick={e=>{stopReferenceAudio();setReviewId(r.id);const menu=e.currentTarget.closest('details');if(menu){menu.open=false;menu.querySelector('summary')?.focus();}}}><span className="question-number">{(i+1).toLocaleString(lang)}</span><span dir="auto">{r.question.question[session.language]}</span></button>)}</div></details>}</div><ReferenceReview key={reviewed.attempts.at(-1)!.id} record={reviewed} lang={lang} disabled={busy} referenceAudioActive={referenceAudio} onListenReference={config?.voice.configured?()=>void listenReference():undefined} onRetry={point=>void action('retry',{recordId:reviewed.id,focusPointId:point?.startsWith('quality:')||point?.startsWith('delivery:')?undefined:point,focusQualityId:point?.startsWith('quality:')?point.slice(8):undefined,focusAudioCriterion:point?.startsWith('delivery:')&&point.slice(9) in AUDIO_CRITERIA?point.slice(9):undefined},false)}/></div>}
 {reportView&&!reviewing&&session?.ended&&!reviewed&&<p className="training-review-empty">{ar?'انتهى الحوار دون إجابة قابلة للمراجعة. ابدأ حوارًا جديدًا عندما تكون مستعدًا.':'This conversation ended without an answer to review. Start a new conversation when you’re ready.'}</p>}
 {captureWarning&&<p role="status" className="scope-note">{ar?'تعذّر حفظ التسجيل على هذا الجهاز. يمكنك متابعة الحوار ومراجعة الإجابة نصيًا.':'The recording could not be saved on this device. You can continue the conversation and review your answer as text.'}</p>}
 {storageError&&<p role="alert">{ar?'تعذّر حفظ رابط الاستئناف في هذا المتصفح.':'Could not save the resume link in this browser.'}</p>}
 {reportView&&!reviewing&&<button type="button" className="text-button" aria-pressed={reviewCapture} onClick={()=>setReviewCapture(!reviewCapture)}>{reviewCapture?(ar?'إيقاف حفظ التسجيل للمحاولة التالية':'Turn off recording for the next attempt'):(ar?'تفعيل حفظ التسجيل للمحاولة التالية':'Turn on recording for the next attempt')}</button>}
 {reportView&&!reviewing&&<div className="review-exit"><button className="text-button" onClick={()=>{stopReferenceAudio();setSession(null);setToken('');setReviewId('');}}>{ar?'بدء حوار جديد':'Start a new conversation'}</button></div>}
 <details className="saved-sessions"><summary>{ar?'حوارات محفوظة':'Saved conversations'} ({saved.length})</summary><p className="retention-note">{ar?'تُحفظ النصوص والمراجعات على الخادم. يحفظ هذا المتصفح رابط الوصول الخاص؛ لا تشاركه. تُحذف السجلات المستضافة بعد ٣٠ يومًا دون تحديث.':'Transcripts and reviews are saved on the server. This browser retains a private access link; do not share it. Hosted records expire after 30 days without updates.'}</p>{saved.map(item=><div key={item.id}><span>{item.contentPractice?(ar?'تدرّب على المحتوى':'Content practice'):traditionLabels[item.tradition]?.[lang]} · {new Date(item.at).toLocaleDateString(lang)}</span><button className="text-button" disabled={busy||call||recording||active} onClick={async()=>{try{const s=await api<TrainingSession>('/api/training/session/read',{token:item.token});setSession(s);setToken(item.token);setError('');}catch(e){fail(e);}}}>{ar?'فتح':'Open'}</button><button className="text-button" disabled={busy||call||recording||active} onClick={async()=>{try{await api('/api/training/session/delete',{token:item.token});try{await deleteSessionMedia(item.id);}catch{setError('local_recording_delete_failed');}const next=saved.filter(v=>v.id!==item.id);localStorage.setItem(storageKey,JSON.stringify(next));setSaved(next);if(session?.id===item.id){setSession(null);setToken('');}}catch(e){fail(e);}}}>{ar?'حذف':'Delete'}</button></div>)}</details>
 {hasLegacy&&!active&&!call&&<a className="text-button" href={`/?app=training&legacy=1&lang=${lang}`}>{ar?'فتح سجلات التدريب السابقة':'Open earlier practice records'}</a>}
 </section>;
}
