import {useState} from 'react';
import type {Lang} from './content';
import {VISUAL_ASPECTS,type VisualEditorial} from './visualEditorial';
export function VisualEditorialPanel({value,lang,onChange,onSeek}:{value:VisualEditorial;lang:Lang;onChange:(value:VisualEditorial)=>void;onSeek:(at:number)=>void}){
 const ar=lang==='ar',[selected,setSelected]=useState(value.frames[0]?.id);const frame=value.frames.find(f=>f.id===selected)||value.frames[0];
 function update(id:string,patch:Partial<VisualEditorial['findings'][number]>){onChange({...value,findings:value.findings.map(f=>f.id===id?{...f,...patch}:f)});}
 return <section className="visual-editorial"><header><span className="eyebrow">{ar?'طبقة المراجعة البصرية':'VISUAL EDITORIAL LAYER'}</span><h2>{ar?'الصورة وما توصله للجمهور':'What the visuals communicate'}</h2><p>{value.summary}</p></header><p className="scope-note">{ar?'هذه ملاحظات بصرية تحريرية، دون استرجاع مصادر. لا تثبت صحة الادعاءات أو الموافقة الدينية؛ مراجعة النصوص والمراجع منفصلة.':'These are visual editorial observations without source retrieval. They do not establish factual truth or religious approval; text and source review are separate.'} {value.kind==='video'?(ar?`فُحصت ${value.frames.length} لقطات فقط؛ قد تفوت أحداث بين اللقطات. لا يشمل هذا المسار الصوت أو الحركة المستمرة.`:`Only ${value.frames.length} sampled frames were inspected. Events between them may be missed; this layer does not assess audio or continuous motion.`):''}</p>
 <div className="visual-editorial-layout"><aside className="visual-editorial-evidence">{frame&&<><figure><img src={frame.image} alt={value.descriptions.find(d=>d.frameId===frame.id)?.description||''}/><figcaption>{value.kind==='video'?`${frame.at.toLocaleString(lang,{maximumFractionDigits:1})} ${ar?'ثانية':'seconds'}`:ar?'الصورة الأصلية':'Original image'}</figcaption></figure><p>{value.descriptions.find(d=>d.frameId===frame.id)?.description}</p>{value.kind==='video'&&<button className="secondary" onClick={()=>onSeek(frame.at)}>{ar?'شاهد هذا الموضع في الفيديو':'View this moment in the video'}</button>}</>}{value.kind==='video'&&<div className="visual-frame-strip">{value.frames.map(f=><button key={f.id} aria-label={`${ar?'اعرض اللقطة':'View frame'} ${f.at.toFixed(1)}`} aria-pressed={selected===f.id} onClick={()=>setSelected(f.id)}><img src={f.image} alt=""/><span>{f.at.toFixed(1)}s</span></button>)}</div>}</aside>
 <div className="visual-editorial-findings">{!value.findings.length&&<p>{ar?'لم تُسجّل ملاحظات بصرية محددة في العينات؛ هذا ليس تصريحًا بالنشر.':'No specific visual findings were recorded in these samples; this is not publication clearance.'}</p>}{value.findings.map(f=><article key={f.id} data-status={f.status}><header><h3>{VISUAL_ASPECTS[f.aspect][lang]}</h3><span>{f.status==='strength'?(ar?'نقطة فعّالة':'Effective choice'):f.status==='attention'?(ar?'اقتراح قبل النشر':'Before publishing'):(ar?'يحتاج إلى سياق':'Context needed')}</span></header><strong>{f.observation}</strong><p>{f.reasoning}</p>{f.suggestion&&<div className="visual-suggestion">{f.suggestion}</div>}<div className="visual-evidence-links">{f.frameIds.map(id=><button className="text-button" key={id} onClick={()=>{setSelected(id);document.querySelector('.visual-editorial-evidence')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}}>{ar?'اعرض الدليل البصري':'Show visual evidence'}{value.kind==='video'?` · ${value.frames.find(g=>g.id===id)?.at.toFixed(1)}s`:''}</button>)}</div><div className="assessment-decisions">{(['accepted','rejected','edited'] as const).map((decision,i)=><button key={decision} aria-pressed={f.decision===decision} onClick={()=>update(f.id,{decision})}>{ar?['قبول الملاحظة','رفض الملاحظة','تعديل الملاحظة'][i]:['Accept finding','Reject finding','Edit finding'][i]}</button>)}</div>{f.decision==='edited'&&<label>{ar?'اقتراحك التحريري':'Your editorial suggestion'}<textarea value={f.editedSuggestion} onChange={e=>update(f.id,{editedSuggestion:e.target.value})}/></label>}<label>{ar?'ملاحظة المراجع':'Reviewer note'}<textarea value={f.reviewerNote} onChange={e=>update(f.id,{reviewerNote:e.target.value})}/></label></article>)}</div></div>
 </section>;
}
